/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-27 05:46:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates._2yong;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _2yong_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/2yong/2yong.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"vsc-initialized\" style=\"margin:0px\" >\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <header id=\"menu\">\r\n");
      out.write("            <section>\r\n");
      out.write("                <div>\r\n");
      out.write("                <img style=\"width: 150px;\r\n");
      out.write("   					 height: 150px;\r\n");
      out.write("    				margin-left: -90px;\r\n");
      out.write("    				margin-top: -33px;\" \r\n");
      out.write("    				src=\"../../static/image/3.png\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <h1>                 \r\n");
      out.write("                    <a href=\"\" id=\"bannertext\">Save The Animal Relationship</a>\r\n");
      out.write("                </h1>\r\n");
      out.write("                <ul class=\"gnb_pc\" >\r\n");
      out.write("                    <li><a class=\"bannertext\" href=\"\">내주변</a></li>\r\n");
      out.write("                    <li><a class=\"bannertext\" href=\"\">예약내역</a></li>\r\n");
      out.write("                    <li><a class=\"bannertext\" href=\"\">더보기</a></li>\r\n");
      out.write("                    <li><a class=\"bannertext\" href=\"\">로그인</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </section>\r\n");
      out.write("        </header>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"sub_top_wrap\">\r\n");
      out.write("    <div class=\"sub_top bg_kong_2\">\r\n");
      out.write("      <h2\r\n");
      out.write("    >\r\n");
      out.write("      STAR 후기\r\n");
      out.write("    </h2>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("    <div id=\"__next\">\r\n");
      out.write("      <div>\r\n");
      out.write("        <div class=\"wrapper\">\r\n");
      out.write("          <div id=\"insurance-container\">\r\n");
      out.write("            <div class=\"desktop hidden-s\">\r\n");
      out.write("              <section class=\"content-section\">\r\n");
      out.write("\r\n");
      out.write("                <div style=\"margin: 0px auto; width: 1000px\">\r\n");
      out.write("                  <div\r\n");
      out.write("                    style=\"\r\n");
      out.write("                      font-size: 23px;\r\n");
      out.write("                      color: rgb(85, 85, 85);\r\n");
      out.write("                      font-weight: 600;\r\n");
      out.write("                      margin-bottom: 80px;\r\n");
      out.write("                    \"\r\n");
      out.write("                  >\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div>\r\n");
      out.write("\r\n");
      out.write("                  <div style=\"display: block; text-align: center;\">\r\n");
      out.write("                    <div id=\"review-list-desktop\" class=\"my-masonry-grid\">\r\n");
      out.write("\r\n");
      out.write("                        <div id=\"2yong_odd\" class=\"my-masonry-grid_column\" style=width:50%;\">\r\n");
      out.write("                        <!-- 왼쪽 -->\r\n");
      out.write("\r\n");
      out.write("                        <div id=\"1\" style=\"display: flex; flex-direction: column; vertical-align: top; border-radius: 10px; box-shadow: rgb(235, 235, 235) 0px 2px 12px 0px; align-items: center;\">\r\n");
      out.write("                          <a href=\"../../templates/2yong/zasehan2yong.jsp\" style=\"padding-bottom: 38px; display: flex; flex-direction: column;\">\r\n");
      out.write("                          <div style=\"display: flex; padding-top: 32px; justify-content: space-between; width: 417px;\"><div style=\"display: flex;\"><div style=\"display: flex; position: relative;\">\r\n");
      out.write("                          <img src=\"https://wayo.cdn.ntruss.com/resized/pet/e7c075c8d9bf40f8a106b2b820da54c3.jpg\" style=\"width: 50px; height: 50px; border-radius: 50%; object-fit: cover;\"></div>\r\n");
      out.write("                          <div style=\"display: flex; flex-direction: column; margin-left: 24px;\"><h1 id=\"2yong_jiyeok1\" style=\"font-size: 20px; line-height: 23px; color: rgb(57, 60, 71); margin-bottom: 6px; display: flex; align-items: center; letter-spacing: -0.2px; text-align: left;\">지역</h1>\r\n");
      out.write("                          <div style=\"display: flex; align-items: center;\"><div style=\"display: flex; flex-direction: column; align-items: flex-end;\"><p id=\"2yong_name1\">이름1</p></div></div></div></div></div>\r\n");
      out.write("                          <p id=\"2yong_hugi1\" style=\"font-size: 15px; font-weight: 400; color: rgb(85, 85, 85); width: 343px; margin-top: 18.5px; overflow: hidden; word-break: break-all; white-space: normal; text-align: left; text-overflow: ellipsis; display: -webkit-box; -webkit-line-clamp: 5; -webkit-box-orient: vertical; overflow-wrap: break-word; line-height: 24px; align-self: flex-end;\">\r\n");
      out.write("                            여기는 후기칸1</p>\r\n");
      out.write("                          <div style=\"margin-top: 28px; background-color: rgb(250, 250, 252); width: 343px; height: 40px; border-radius: 20px; display: flex; flex-direction: row; justify-content: center; align-items: center; align-self: flex-end;\"><span style=\"font-size: 20px; margin-bottom: 0px; color: rgb(95, 99, 108); margin-right: 3px;\">+</span><p style=\"font-weight: 600; color: rgb(95, 99, 108); font-size: 14px; line-height: 40px;\"> 내용 더 보기</p></div></a></div>\r\n");
      out.write("\r\n");
      out.write("                          <div id=\"3\" style=\"display: flex; flex-direction: column; vertical-align: top; border-radius: 10px; box-shadow: rgb(235, 235, 235) 0px 2px 12px 0px; align-items: center;\">\r\n");
      out.write("                            <a href=\"zasehan2yong.html\" style=\"padding-bottom: 38px; display: flex; flex-direction: column;\">\r\n");
      out.write("                            <div style=\"display: flex; padding-top: 32px; justify-content: space-between; width: 417px;\"><div style=\"display: flex;\"><div style=\"display: flex; position: relative;\">\r\n");
      out.write("                            <img src=\"https://wayo.cdn.ntruss.com/resized/pet/e7c075c8d9bf40f8a106b2b820da54c3.jpg\" style=\"width: 50px; height: 50px; border-radius: 50%; object-fit: cover;\"></div>\r\n");
      out.write("                            <div style=\"display: flex; flex-direction: column; margin-left: 24px;\"><h1 id=\"2yong_jiyeok3\" style=\"font-size: 20px; line-height: 23px; color: rgb(57, 60, 71); margin-bottom: 6px; display: flex; align-items: center; letter-spacing: -0.2px; text-align: left;\">지역</h1>\r\n");
      out.write("                            <div style=\"display: flex; align-items: center;\"><div style=\"display: flex; flex-direction: column; align-items: flex-end;\"><p id=\"2yong_name3\">이름3</p></div></div></div></div></div>\r\n");
      out.write("                            <p id=\"2yong_hugi3\" style=\"font-size: 15px; font-weight: 400; color: rgb(85, 85, 85); width: 343px; margin-top: 18.5px; overflow: hidden; word-break: break-all; white-space: normal; text-align: left; text-overflow: ellipsis; display: -webkit-box; -webkit-line-clamp: 5; -webkit-box-orient: vertical; overflow-wrap: break-word; line-height: 24px; align-self: flex-end;\">\r\n");
      out.write("                              여기는 후기칸3</p>\r\n");
      out.write("                            <div style=\"margin-top: 28px; background-color: rgb(250, 250, 252); width: 343px; height: 40px; border-radius: 20px; display: flex; flex-direction: row; justify-content: center; align-items: center; align-self: flex-end;\"><span style=\"font-size: 20px; margin-bottom: 0px; color: rgb(95, 99, 108); margin-right: 3px;\">+</span><p style=\"font-weight: 600; color: rgb(95, 99, 108); font-size: 14px; line-height: 40px;\"> 내용 더 보기</p></div></a></div>\r\n");
      out.write("\r\n");
      out.write("                            <div id=\"5\" style=\"display: flex; flex-direction: column; vertical-align: top; border-radius: 10px; box-shadow: rgb(235, 235, 235) 0px 2px 12px 0px; align-items: center;\">\r\n");
      out.write("                              <a href=\"zasehan2yong.html\" style=\"padding-bottom: 38px; display: flex; flex-direction: column;\">\r\n");
      out.write("                              <div style=\"display: flex; padding-top: 32px; justify-content: space-between; width: 417px;\"><div style=\"display: flex;\"><div style=\"display: flex; position: relative;\">\r\n");
      out.write("                              <img src=\"https://wayo.cdn.ntruss.com/resized/pet/e7c075c8d9bf40f8a106b2b820da54c3.jpg\" style=\"width: 50px; height: 50px; border-radius: 50%; object-fit: cover;\"></div>\r\n");
      out.write("                              <div style=\"display: flex; flex-direction: column; margin-left: 24px;\"><h1 id=\"2yong_jiyeok5\" style=\"font-size: 20px; line-height: 23px; color: rgb(57, 60, 71); margin-bottom: 6px; display: flex; align-items: center; letter-spacing: -0.2px; text-align: left;\">지역</h1>\r\n");
      out.write("                              <div style=\"display: flex; align-items: center;\"><div style=\"display: flex; flex-direction: column; align-items: flex-end;\"><p id=\"2yong_name5\">이름5</p></div></div></div></div></div>\r\n");
      out.write("                              <p id=\"2yong_hugi5\" style=\"font-size: 15px; font-weight: 400; color: rgb(85, 85, 85); width: 343px; margin-top: 18.5px; overflow: hidden; word-break: break-all; white-space: normal; text-align: left; text-overflow: ellipsis; display: -webkit-box; -webkit-line-clamp: 5; -webkit-box-orient: vertical; overflow-wrap: break-word; line-height: 24px; align-self: flex-end;\">\r\n");
      out.write("                                여기는 후기칸5</p>\r\n");
      out.write("                              <div style=\"margin-top: 28px; background-color: rgb(250, 250, 252); width: 343px; height: 40px; border-radius: 20px; display: flex; flex-direction: row; justify-content: center; align-items: center; align-self: flex-end;\"><span style=\"font-size: 20px; margin-bottom: 0px; color: rgb(95, 99, 108); margin-right: 3px;\">+</span><p style=\"font-weight: 600; color: rgb(95, 99, 108); font-size: 14px; line-height: 40px;\"> 내용 더 보기</p></div></a></div>\r\n");
      out.write("\r\n");
      out.write("                              <div id=\"7\" style=\"display: flex; flex-direction: column; vertical-align: top; border-radius: 10px; box-shadow: rgb(235, 235, 235) 0px 2px 12px 0px; align-items: center;\">\r\n");
      out.write("                                <a href=\"zasehan2yong.html\" style=\"padding-bottom: 38px; display: flex; flex-direction: column;\">\r\n");
      out.write("                                <div style=\"display: flex; padding-top: 32px; justify-content: space-between; width: 417px;\"><div style=\"display: flex;\"><div style=\"display: flex; position: relative;\">\r\n");
      out.write("                                <img src=\"https://wayo.cdn.ntruss.com/resized/pet/e7c075c8d9bf40f8a106b2b820da54c3.jpg\" style=\"width: 50px; height: 50px; border-radius: 50%; object-fit: cover;\"></div>\r\n");
      out.write("                                <div style=\"display: flex; flex-direction: column; margin-left: 24px;\"><h1 id=\"2yong_jiyeok7\" style=\"font-size: 20px; line-height: 23px; color: rgb(57, 60, 71); margin-bottom: 6px; display: flex; align-items: center; letter-spacing: -0.2px; text-align: left;\">지역</h1>\r\n");
      out.write("                                <div style=\"display: flex; align-items: center;\"><div style=\"display: flex; flex-direction: column; align-items: flex-end;\"><p id=\"2yong_name7\">이름7</p></div></div></div></div></div>\r\n");
      out.write("                                <p id=\"2yong_hugi7\" style=\"font-size: 15px; font-weight: 400; color: rgb(85, 85, 85); width: 343px; margin-top: 18.5px; overflow: hidden; word-break: break-all; white-space: normal; text-align: left; text-overflow: ellipsis; display: -webkit-box; -webkit-line-clamp: 5; -webkit-box-orient: vertical; overflow-wrap: break-word; line-height: 24px; align-self: flex-end;\">\r\n");
      out.write("                                  여기는 후기칸7</p>\r\n");
      out.write("                                <div style=\"margin-top: 28px; background-color: rgb(250, 250, 252); width: 343px; height: 40px; border-radius: 20px; display: flex; flex-direction: row; justify-content: center; align-items: center; align-self: flex-end;\"><span style=\"font-size: 20px; margin-bottom: 0px; color: rgb(95, 99, 108); margin-right: 3px;\">+</span><p style=\"font-weight: 600; color: rgb(95, 99, 108); font-size: 14px; line-height: 40px;\"> 내용 더 보기</p></div></a></div>\r\n");
      out.write("\r\n");
      out.write("                                <div id=\"9\" style=\"display: flex; flex-direction: column; vertical-align: top; border-radius: 10px; box-shadow: rgb(235, 235, 235) 0px 2px 12px 0px; align-items: center;\">\r\n");
      out.write("                                  <a href=\"zasehan2yong.html\" style=\"padding-bottom: 38px; display: flex; flex-direction: column;\">\r\n");
      out.write("                                  <div style=\"display: flex; padding-top: 32px; justify-content: space-between; width: 417px;\"><div style=\"display: flex;\"><div style=\"display: flex; position: relative;\">\r\n");
      out.write("                                  <img src=\"https://wayo.cdn.ntruss.com/resized/pet/e7c075c8d9bf40f8a106b2b820da54c3.jpg\" style=\"width: 50px; height: 50px; border-radius: 50%; object-fit: cover;\"></div>\r\n");
      out.write("                                  <div style=\"display: flex; flex-direction: column; margin-left: 24px;\"><h1 id=\"2yong_jiyeok9\" style=\"font-size: 20px; line-height: 23px; color: rgb(57, 60, 71); margin-bottom: 6px; display: flex; align-items: center; letter-spacing: -0.2px; text-align: left;\">지역</h1>\r\n");
      out.write("                                  <div style=\"display: flex; align-items: center;\"><div style=\"display: flex; flex-direction: column; align-items: flex-end;\"><p id=\"2yong_name9\">이름9</p></div></div></div></div></div>\r\n");
      out.write("                                  <p id=\"2yong_hugi9\" style=\"font-size: 15px; font-weight: 400; color: rgb(85, 85, 85); width: 343px; margin-top: 18.5px; overflow: hidden; word-break: break-all; white-space: normal; text-align: left; text-overflow: ellipsis; display: -webkit-box; -webkit-line-clamp: 5; -webkit-box-orient: vertical; overflow-wrap: break-word; line-height: 24px; align-self: flex-end;\">\r\n");
      out.write("                                    여기는 후기칸9</p>\r\n");
      out.write("                                  <div style=\"margin-top: 28px; background-color: rgb(250, 250, 252); width: 343px; height: 40px; border-radius: 20px; display: flex; flex-direction: row; justify-content: center; align-items: center; align-self: flex-end;\"><span style=\"font-size: 20px; margin-bottom: 0px; color: rgb(95, 99, 108); margin-right: 3px;\">+</span><p style=\"font-weight: 600; color: rgb(95, 99, 108); font-size: 14px; line-height: 40px;\"> 내용 더 보기</p></div></a></div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("        <!-- 오른쪽 -->\r\n");
      out.write("<div id=\"2yong_even\" class=\"my-masonry-grid_column\" style=width:50%;\">\r\n");
      out.write("\r\n");
      out.write("                        <div id=\"2\" style=\"display: flex; flex-direction: column; vertical-align: top; border-radius: 10px; box-shadow: rgb(235, 235, 235) 0px 2px 12px 0px; align-items: center;\">\r\n");
      out.write("                          <a href=\"zasehan2yong.html\" style=\"padding-bottom: 38px; display: flex; flex-direction: column;\">\r\n");
      out.write("                          <div style=\"display: flex; padding-top: 32px; justify-content: space-between; width: 417px;\"><div style=\"display: flex;\"><div style=\"display: flex; position: relative;\">\r\n");
      out.write("                          <img src=\"https://wayo.cdn.ntruss.com/resized/pet/e7c075c8d9bf40f8a106b2b820da54c3.jpg\" style=\"width: 50px; height: 50px; border-radius: 50%; object-fit: cover;\"></div>\r\n");
      out.write("                          <div style=\"display: flex; flex-direction: column; margin-left: 24px;\"><h1 id=\"2yong_jiyeok2\" style=\"font-size: 20px; line-height: 23px; color: rgb(57, 60, 71); margin-bottom: 6px; display: flex; align-items: center; letter-spacing: -0.2px; text-align: left;\">지역</h1>\r\n");
      out.write("                          <div style=\"display: flex; align-items: center;\"><div style=\"display: flex; flex-direction: column; align-items: flex-end;\"><p id=\"2yong_name2\">이름2</p></div></div></div></div></div>\r\n");
      out.write("                          <p id=\"2yong_hugi2\" style=\"font-size: 15px; font-weight: 400; color: rgb(85, 85, 85); width: 343px; margin-top: 18.5px; overflow: hidden; word-break: break-all; white-space: normal; text-align: left; text-overflow: ellipsis; display: -webkit-box; -webkit-line-clamp: 5; -webkit-box-orient: vertical; overflow-wrap: break-word; line-height: 24px; align-self: flex-end;\">\r\n");
      out.write("                            여기는 후기칸2</p>\r\n");
      out.write("                          <div style=\"margin-top: 28px; background-color: rgb(250, 250, 252); width: 343px; height: 40px; border-radius: 20px; display: flex; flex-direction: row; justify-content: center; align-items: center; align-self: flex-end;\"><span style=\"font-size: 20px; margin-bottom: 0px; color: rgb(95, 99, 108); margin-right: 3px;\">+</span><p style=\"font-weight: 600; color: rgb(95, 99, 108); font-size: 14px; line-height: 40px;\"> 내용 더 보기</p></div></a></div>\r\n");
      out.write("\r\n");
      out.write("                          <div id=\"4\" style=\"display: flex; flex-direction: column; vertical-align: top; border-radius: 10px; box-shadow: rgb(235, 235, 235) 0px 2px 12px 0px; align-items: center;\">\r\n");
      out.write("                            <a href=\"zasehan2yong.html\" style=\"padding-bottom: 38px; display: flex; flex-direction: column;\">\r\n");
      out.write("                            <div style=\"display: flex; padding-top: 32px; justify-content: space-between; width: 417px;\"><div style=\"display: flex;\"><div style=\"display: flex; position: relative;\">\r\n");
      out.write("                            <img src=\"https://wayo.cdn.ntruss.com/resized/pet/e7c075c8d9bf40f8a106b2b820da54c3.jpg\" style=\"width: 50px; height: 50px; border-radius: 50%; object-fit: cover;\"></div>\r\n");
      out.write("                            <div style=\"display: flex; flex-direction: column; margin-left: 24px;\"><h1 id=\"2yong_jiyeok4\" style=\"font-size: 20px; line-height: 23px; color: rgb(57, 60, 71); margin-bottom: 6px; display: flex; align-items: center; letter-spacing: -0.2px; text-align: left;\">지역</h1>\r\n");
      out.write("                            <div style=\"display: flex; align-items: center;\"><div style=\"display: flex; flex-direction: column; align-items: flex-end;\"><p id=\"2yong_name4\">이름4</p></div></div></div></div></div>\r\n");
      out.write("                            <p id=\"2yong_hugi4\" style=\"font-size: 15px; font-weight: 400; color: rgb(85, 85, 85); width: 343px; margin-top: 18.5px; overflow: hidden; word-break: break-all; white-space: normal; text-align: left; text-overflow: ellipsis; display: -webkit-box; -webkit-line-clamp: 5; -webkit-box-orient: vertical; overflow-wrap: break-word; line-height: 24px; align-self: flex-end;\">\r\n");
      out.write("                              여기는 후기칸4</p>\r\n");
      out.write("                            <div style=\"margin-top: 28px; background-color: rgb(250, 250, 252); width: 343px; height: 40px; border-radius: 20px; display: flex; flex-direction: row; justify-content: center; align-items: center; align-self: flex-end;\"><span style=\"font-size: 20px; margin-bottom: 0px; color: rgb(95, 99, 108); margin-right: 3px;\">+</span><p style=\"font-weight: 600; color: rgb(95, 99, 108); font-size: 14px; line-height: 40px;\"> 내용 더 보기</p></div></a></div>\r\n");
      out.write("\r\n");
      out.write("                            <div id=\"6\" style=\"display: flex; flex-direction: column; vertical-align: top; border-radius: 10px; box-shadow: rgb(235, 235, 235) 0px 2px 12px 0px; align-items: center;\">\r\n");
      out.write("                              <a href=\"zasehan2yong.html\" style=\"padding-bottom: 38px; display: flex; flex-direction: column;\">\r\n");
      out.write("                              <div style=\"display: flex; padding-top: 32px; justify-content: space-between; width: 417px;\"><div style=\"display: flex;\"><div style=\"display: flex; position: relative;\">\r\n");
      out.write("                              <img src=\"https://wayo.cdn.ntruss.com/resized/pet/e7c075c8d9bf40f8a106b2b820da54c3.jpg\" style=\"width: 50px; height: 50px; border-radius: 50%; object-fit: cover;\"></div>\r\n");
      out.write("                              <div style=\"display: flex; flex-direction: column; margin-left: 24px;\"><h1 id=\"2yong_jiyeok6\" style=\"font-size: 20px; line-height: 23px; color: rgb(57, 60, 71); margin-bottom: 6px; display: flex; align-items: center; letter-spacing: -0.2px; text-align: left;\">지역</h1>\r\n");
      out.write("                              <div style=\"display: flex; align-items: center;\"><div style=\"display: flex; flex-direction: column; align-items: flex-end;\"><p id=\"2yong_name6\">이름6</p></div></div></div></div></div>\r\n");
      out.write("                              <p id=\"2yong_hugi6\" style=\"font-size: 15px; font-weight: 400; color: rgb(85, 85, 85); width: 343px; margin-top: 18.5px; overflow: hidden; word-break: break-all; white-space: normal; text-align: left; text-overflow: ellipsis; display: -webkit-box; -webkit-line-clamp: 5; -webkit-box-orient: vertical; overflow-wrap: break-word; line-height: 24px; align-self: flex-end;\">\r\n");
      out.write("                                여기는 후기칸6</p>\r\n");
      out.write("                              <div style=\"margin-top: 28px; background-color: rgb(250, 250, 252); width: 343px; height: 40px; border-radius: 20px; display: flex; flex-direction: row; justify-content: center; align-items: center; align-self: flex-end;\"><span style=\"font-size: 20px; margin-bottom: 0px; color: rgb(95, 99, 108); margin-right: 3px;\">+</span><p style=\"font-weight: 600; color: rgb(95, 99, 108); font-size: 14px; line-height: 40px;\"> 내용 더 보기</p></div></a></div>\r\n");
      out.write("\r\n");
      out.write("                              <div id=\"8\" style=\"display: flex; flex-direction: column; vertical-align: top; border-radius: 10px; box-shadow: rgb(235, 235, 235) 0px 2px 12px 0px; align-items: center;\">\r\n");
      out.write("                                <a href=\"zasehan2yong.html\" style=\"padding-bottom: 38px; display: flex; flex-direction: column;\">\r\n");
      out.write("                                <div style=\"display: flex; padding-top: 32px; justify-content: space-between; width: 417px;\"><div style=\"display: flex;\"><div style=\"display: flex; position: relative;\">\r\n");
      out.write("                                <img src=\"https://wayo.cdn.ntruss.com/resized/pet/e7c075c8d9bf40f8a106b2b820da54c3.jpg\" style=\"width: 50px; height: 50px; border-radius: 50%; object-fit: cover;\"></div>\r\n");
      out.write("                                <div style=\"display: flex; flex-direction: column; margin-left: 24px;\"><h1 id=\"2yong_jiyeok8\" style=\"font-size: 20px; line-height: 23px; color: rgb(57, 60, 71); margin-bottom: 6px; display: flex; align-items: center; letter-spacing: -0.2px; text-align: left;\">지역</h1>\r\n");
      out.write("                                <div style=\"display: flex; align-items: center;\"><div style=\"display: flex; flex-direction: column; align-items: flex-end;\"><p id=\"2yong_name8\">이름8</p></div></div></div></div></div>\r\n");
      out.write("                                <p id=\"2yong_hugi8\" style=\"font-size: 15px; font-weight: 400; color: rgb(85, 85, 85); width: 343px; margin-top: 18.5px; overflow: hidden; word-break: break-all; white-space: normal; text-align: left; text-overflow: ellipsis; display: -webkit-box; -webkit-line-clamp: 5; -webkit-box-orient: vertical; overflow-wrap: break-word; line-height: 24px; align-self: flex-end;\">\r\n");
      out.write("                                  여기는 후기칸8</p>\r\n");
      out.write("                                <div style=\"margin-top: 28px; background-color: rgb(250, 250, 252); width: 343px; height: 40px; border-radius: 20px; display: flex; flex-direction: row; justify-content: center; align-items: center; align-self: flex-end;\"><span style=\"font-size: 20px; margin-bottom: 0px; color: rgb(95, 99, 108); margin-right: 3px;\">+</span><p style=\"font-weight: 600; color: rgb(95, 99, 108); font-size: 14px; line-height: 40px;\"> 내용 더 보기</p></div></a></div>\r\n");
      out.write("\r\n");
      out.write("                                <div id=\"10\" style=\"display: flex; flex-direction: column; vertical-align: top; border-radius: 10px; box-shadow: rgb(235, 235, 235) 0px 2px 12px 0px; align-items: center;\">\r\n");
      out.write("                                  <a href=\"zasehan2yong.html\" style=\"padding-bottom: 38px; display: flex; flex-direction: column;\">\r\n");
      out.write("                                  <div style=\"display: flex; padding-top: 32px; justify-content: space-between; width: 417px;\"><div style=\"display: flex;\"><div style=\"display: flex; position: relative;\">\r\n");
      out.write("                                  <img src=\"https://wayo.cdn.ntruss.com/resized/pet/e7c075c8d9bf40f8a106b2b820da54c3.jpg\" style=\"width: 50px; height: 50px; border-radius: 50%; object-fit: cover;\"></div>\r\n");
      out.write("                                  <div style=\"display: flex; flex-direction: column; margin-left: 24px;\"><h1 id=\"2yong_jiyeok10\" style=\"font-size: 20px; line-height: 23px; color: rgb(57, 60, 71); margin-bottom: 6px; display: flex; align-items: center; letter-spacing: -0.2px; text-align: left;\">지역</h1>\r\n");
      out.write("                                  <div style=\"display: flex; align-items: center;\"><div style=\"display: flex; flex-direction: column; align-items: flex-end;\"><p id=\"2yong_name10\">이름10</p></div></div></div></div></div>\r\n");
      out.write("                                  <p id=\"2yong_hugi10\" style=\"font-size: 15px; font-weight: 400; color: rgb(85, 85, 85); width: 343px; margin-top: 18.5px; overflow: hidden; word-break: break-all; white-space: normal; text-align: left; text-overflow: ellipsis; display: -webkit-box; -webkit-line-clamp: 5; -webkit-box-orient: vertical; overflow-wrap: break-word; line-height: 24px; align-self: flex-end;\">\r\n");
      out.write("                                    여기는 후기칸10</p>\r\n");
      out.write("                                  <div style=\"margin-top: 28px; background-color: rgb(250, 250, 252); width: 343px; height: 40px; border-radius: 20px; display: flex; flex-direction: row; justify-content: center; align-items: center; align-self: flex-end;\"><span style=\"font-size: 20px; margin-bottom: 0px; color: rgb(95, 99, 108); margin-right: 3px;\">+</span><p style=\"font-weight: 600; color: rgb(95, 99, 108); font-size: 14px; line-height: 40px;\"> 내용 더 보기</p></div></a></div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </section>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <footer>\r\n");
      out.write("                <div class=\"align\">\r\n");
      out.write("                    <ul class=\"link\">\r\n");
      out.write("                        <li><a href=\"\">서비스문의</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <p><b>고객행복센터 1670-6250</b><span>오전 9시 - 새벽 3시</span></p>\r\n");
      out.write("                    <address>\r\n");
      out.write("                        <span>(주) STAR</span>\r\n");
      out.write("                                        주소 : 서울특별시 강남구 봉은사로 479, 479타워 11층 | 대표이사 : 정명훈 | 사업자등록번호: 742-86-00224 | 전자우편주소 : help@goodchoice.kr<br>\r\n");
      out.write("                        통신판매번호 : 2017-서울강남-01779 | 관광사업자 등록번호: 제1026-24호 | 전화번호 : 1670-6250 | 호스팅서비스제공자의 상호 표시: (주)여기어때컴퍼니<br>\r\n");
      out.write("                        <span class=\"order\">(주) 여기어때컴퍼니는 통신판매중개자로서 통신판매의 당사자가 아니며, 상품의 예약, 이용 및 환불 등과 관련한 의무와 책임은 각 판매자에게 있습니다.</span><br>\r\n");
      out.write("                        Copyright GC COMPANY Corp. All rights reserved.\r\n");
      out.write("                    </address>\r\n");
      out.write("                </div>\r\n");
      out.write("            </footer>\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("  <script>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("const menu = document.querySelector('#menu');\r\n");
      out.write("const bannertext = document.querySelector('#bannertext');\r\n");
      out.write("const banner = document.querySelectorAll('.bannertext');\r\n");
      out.write("const menuHeight = menu.getBoundingClientRect().height;\r\n");
      out.write("\r\n");
      out.write("document.addEventListener('scroll', () => {\r\n");
      out.write("\r\n");
      out.write("  if (window.scrollY > menuHeight) {\r\n");
      out.write("    menu.classList.add('active');\r\n");
      out.write("    bannertext.classList.add('textactive2');\r\n");
      out.write("    for(let i=0; i<banner.length; i++){\r\n");
      out.write("        banner[i].classList.add('textactive');\r\n");
      out.write("    }\r\n");
      out.write("  } else {\r\n");
      out.write("    menu.classList.remove('active');\r\n");
      out.write("    bannertext.classList.remove('textactive2');\r\n");
      out.write("    for(let i=0; i<banner.length; i++){\r\n");
      out.write("        banner[i].classList.remove('textactive');\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
