/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-26 07:14:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates._2yong;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class zasehan2yong_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../../static/css/2yong/zasehan2yong.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"vsc-initialized\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <header id=\"menu\">\r\n");
      out.write("            <section>\r\n");
      out.write("                <div>\r\n");
      out.write("                <img style=\"width: 150px;\r\n");
      out.write("   					 height: 150px;\r\n");
      out.write("    				margin-left: -90px;\r\n");
      out.write("    				margin-top: -33px;\" \r\n");
      out.write("    				src=\"../../static/image/3.png\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <h1>                 \r\n");
      out.write("                    <a href=\"\" id=\"bannertext\">Save The Animal Relationship</a>\r\n");
      out.write("                </h1>\r\n");
      out.write("                <ul class=\"gnb_pc\" >\r\n");
      out.write("                    <li><a class=\"bannertext\" href=\"\">내주변</a></li>\r\n");
      out.write("                    <li><a class=\"bannertext\" href=\"\">예약내역</a></li>\r\n");
      out.write("                    <li><a class=\"bannertext\" href=\"\">더보기</a></li>\r\n");
      out.write("                    <li><a class=\"bannertext\" href=\"\">로그인</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </section>\r\n");
      out.write("        </header>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"sub_top_wrap\">\r\n");
      out.write("      <div class=\"sub_top bg_kong_2\">\r\n");
      out.write("        <h2\r\n");
      out.write("      >\r\n");
      out.write("        STAR 후기\r\n");
      out.write("      </h2>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"insurance-container\">\r\n");
      out.write("    <div class=\"desktop hidden-s\">\r\n");
      out.write("        <section>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div style=\"display:flex;flex-direction:row;justify-content:center;align-items:center;margin-bottom:100px;margin-top: 150px;\">\r\n");
      out.write("                    <h2 style=\"font-weight:300;font-size:39px;line-height:70px;color:#393C47;margin-bottom:0\"><b>후기</b>를 자세히 살펴보세요!</h2></div></div><div>\r\n");
      out.write("\r\n");
      out.write("                        <div id=\"1\" style=\"display:flex;justify-content:center;flex-direction:column;align-items:center;padding-bottom:223px\">\r\n");
      out.write("                            <div style=\"display:flex;align-items:center\"><a id=\"back\" style=\"margin-right:100px\"><img src=\"../../static/image/leftarrow.png\" style=\"filter: opacity(0.5) drop-shadow(0 0 0 #f0e0e0);width:75px;height:60px\"></a>\r\n");
      out.write("                            <div style=\"display:flex;position:relative;flex-direction:column;vertical-align:top;width:640px;border-radius:10px;box-shadow:0px 2px 12px rgba(0,0,0,0.09);padding:38px\">\r\n");
      out.write("                            <div style=\"position:relative\"><div style=\"display:flex;justify-content:space-between\"><div style=\"display:flex\">\r\n");
      out.write("                            <div style=\"display:flex;position:relative;justify-content:center;align-items:center\"><img src=\"https://dugs12pdb1jsf.cloudfront.net/resized/pet/0e4c7c3178e24a96b01a27a332955561.jpg\" style=\"width:50px;height:50px;border-radius:50%;object-fit:cover\"></div>\r\n");
      out.write("                            <div style=\"display:flex;flex-direction:column;margin-left:24px\"><h1 id=\"zasehan_jiyeok\" style=\"font-size:20px;line-height:23px;color:#393C47;margin-bottom:10px;display:flex;align-items:center;letter-spacing:-0.2px\">서울 양천구 신정동</h1>\r\n");
      out.write("                            <div style=\"display:flex;align-items:center\"><p id=\"zasehan_name\">이름</p>\r\n");
      out.write("                            </div></div></div></div>\r\n");
      out.write("                            <p style=\"font-size:15px;font-weight:400;color:#4D5055;margin-top:18.5px;word-break:keep-all;white-space:pre-line;text-align:left;word-wrap:break-word;line-height:30px;align-self:flex-end\" id=\"zasehan_hugi\">\r\n");
      out.write("                            1번</p></div>\r\n");
      out.write("                            <div style=\"display:flex;flex-direction:row;align-self:flex-end;margin-top:27px;flex-wrap:wrap\">\r\n");
      out.write("                            <div style=\"display:flex;flex-direction:row\"></div></div></div>\r\n");
      out.write("                            <a id=\"front\" style=\"margin-left:100px\"><img src=\"../../static/image/leftarrow.png\" style=\"filter: opacity(0.5) drop-shadow(0 0 0 #f0e0e0);width:75px;height:60px;transform:rotateY(180deg)\"></a></div>        \r\n");
      out.write("                            <a href=\"../../templates/2yong/2yong.jsp\" style=\"margin-top:100px;width:304px;height:59px;border:1px solid #6A92FE;border-radius:30px;display:flex;flex-direction:row;justify-content:center;align-items:center\"><span style=\"font-size:26px;margin-bottom:2px;color:#6A92FE;margin-right:6px\">+</span><p style=\"font-weight:600;color:#6A92FE;font-size:18px;line-height:40px\"> 전체 후기 보기</p></a></div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"align\">\r\n");
      out.write("            <ul class=\"link\">\r\n");
      out.write("                <li><a href=\"\">서비스문의</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <p><b>고객행복센터 1670-6250</b><span>오전 9시 - 새벽 3시</span></p>\r\n");
      out.write("            <address>\r\n");
      out.write("                <span>(주) STAR</span>\r\n");
      out.write("                                주소 : 서울특별시 강남구 봉은사로 479, 479타워 11층 | 대표이사 : 정명훈 | 사업자등록번호: 742-86-00224 | 전자우편주소 : help@goodchoice.kr<br>\r\n");
      out.write("                통신판매번호 : 2017-서울강남-01779 | 관광사업자 등록번호: 제1026-24호 | 전화번호 : 1670-6250 | 호스팅서비스제공자의 상호 표시: (주)여기어때컴퍼니<br>\r\n");
      out.write("                <span class=\"order\">(주) 여기어때컴퍼니는 통신판매중개자로서 통신판매의 당사자가 아니며, 상품의 예약, 이용 및 환불 등과 관련한 의무와 책임은 각 판매자에게 있습니다.</span><br>\r\n");
      out.write("                Copyright GC COMPANY Corp. All rights reserved.\r\n");
      out.write("            </address>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("    var hyunzepage = $('#1').attr('id');\r\n");
      out.write("    var idfront_num = Number(hyunzepage)+1==21 ? 20 : Number(hyunzepage)+1;  \r\n");
      out.write("    var idback_num = Number(hyunzepage)-1==0 ? 1 : Number(hyunzepage)-1;\r\n");
      out.write("\r\n");
      out.write("    var idfront = String(idfront_num);\r\n");
      out.write("    var idback = String(idback_num);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    $('#front').click(\r\n");
      out.write("        function(){\r\n");
      out.write("            let idfront_num = Number(hyunzepage)+Number(1)>=Number(11)? Number(10) : Number(hyunzepage)+Number(1);  \r\n");
      out.write("            let idfront = String(idfront_num);\r\n");
      out.write("            hyunzepage = String(idfront_num);\r\n");
      out.write("\r\n");
      out.write("            $('#zasehan_name').load('../../templates/2yong/2yong.jsp #2yong_name'+idfront);\r\n");
      out.write("            $('#zasehan_jiyeok').load('../../templates/2yong/2yong.jsp #2yong_jiyeok'+idfront);\r\n");
      out.write("            $('#zasehan_hugi').load('../../templates/2yong/2yong.jsp #2yong_hugi'+idfront);\r\n");
      out.write("        }\r\n");
      out.write("    )\r\n");
      out.write("\r\n");
      out.write("    $('#back').click(\r\n");
      out.write("        function(){\r\n");
      out.write("            let idback_num = Number(hyunzepage)-Number(1)<=0 ? Number(1) : Number(hyunzepage)-Number(1);\r\n");
      out.write("            let idback = String(idback_num);\r\n");
      out.write("            hyunzepage = String(idback_num);\r\n");
      out.write("            $('#zasehan_name').load('../../templates/2yong/2yong.jsp #2yong_name'+idback);\r\n");
      out.write("            $('#zasehan_jiyeok').load('../../templates/2yong/2yong.jsp #2yong_jiyeok'+idback);\r\n");
      out.write("            $('#zasehan_hugi').load('../../templates/2yong/2yong.jsp #2yong_hugi'+idback);\r\n");
      out.write("        }\r\n");
      out.write("    )\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("const menu = document.querySelector('#menu');\r\n");
      out.write("const bannertext = document.querySelector('#bannertext');\r\n");
      out.write("const banner = document.querySelectorAll('.bannertext');\r\n");
      out.write("const menuHeight = menu.getBoundingClientRect().height;\r\n");
      out.write("\r\n");
      out.write("document.addEventListener('scroll', () => {\r\n");
      out.write("\r\n");
      out.write("  if (window.scrollY > menuHeight) {\r\n");
      out.write("    menu.classList.add('active');\r\n");
      out.write("    bannertext.classList.add('textactive2');\r\n");
      out.write("    for(let i=0; i<banner.length; i++){\r\n");
      out.write("        banner[i].classList.add('textactive');\r\n");
      out.write("    }\r\n");
      out.write("  } else {\r\n");
      out.write("    menu.classList.remove('active');\r\n");
      out.write("    bannertext.classList.remove('textactive2');\r\n");
      out.write("    for(let i=0; i<banner.length; i++){\r\n");
      out.write("        banner[i].classList.remove('textactive');\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
