/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-16 09:05:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class FAQ_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>자주 묻는 질문</title>\r\n");
      out.write("<link href=\"../static/css/FAQ.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"wrap show\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <header>\r\n");
      out.write("\r\n");
      out.write("        <section>\r\n");
      out.write("            <h1><a class=\"\" href=\"https://www.goodchoice.kr/\" title=\"여기어때\">STAR</a></h1>\r\n");
      out.write("            <button type=\"button\" class=\"btn_menu nav_open \">메뉴</button>\r\n");
      out.write("            <button type=\"button\" class=\"btn_srch srch_open \">검색</button>\r\n");
      out.write("            <ul class=\"gnb_pc\">\r\n");
      out.write("                    <li><a href=\"\">Main Category1</a></li>\r\n");
      out.write("                    <li><a href=\"\">Main Category2</a></li>\r\n");
      out.write("                    <li class=\"over\">\r\n");
      out.write("                    <button type=\"button\"><span>더보기</span></button>\r\n");
      out.write("                    <ul class=\"list_03\" style=\"display: none; opacity: 1;\">\r\n");
      out.write("	                    <li><a href=\"https://www.goodchoice.kr/more/faq\">자주 묻는 질문</a></li>\r\n");
      out.write("	                    <li><a href=\"https://www.goodchoice.kr/more/inquiry\">1:1 문의</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <!-- Search -->\r\n");
      out.write("            <div class=\"srch_bar\">\r\n");
      out.write("                <div class=\"wrap_inp\">\r\n");
      out.write("                    <input type=\"text\" id=\"keyword\" placeholder=\"지역, 숙소명\" autocomplete=\"off\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn_srch\">검색</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button class=\"btn_cancel\" onclick=\"srch_close()\">취소</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- //Search -->\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- 추천검색어 -->\r\n");
      out.write("    <div class=\"recommend_srch\">\r\n");
      out.write("        <div class=\"scroll_srch\">\r\n");
      out.write("            <div class=\"scroller\">\r\n");
      out.write("                <div class=\"default\" style=\"display:block\">\r\n");
      out.write("                    <strong>추천 검색어</strong>\r\n");
      out.write("                    <ul></ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 연관검색어 -->\r\n");
      out.write("                <div class=\"chain\">\r\n");
      out.write("                    <ul></ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/more.css?rand=1680259775\">\r\n");
      out.write("\r\n");
      out.write("<!-- Sub Top -->\r\n");
      out.write("<div class=\"sub_top_wrap\">\r\n");
      out.write("	<div class=\"sub_top bg_kong_3\">\r\n");
      out.write("		<h2>더보기</h2>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //Sub Top -->\r\n");
      out.write("\r\n");
      out.write("<!-- Content  -->\r\n");
      out.write("<div id=\"content\" class=\"sub_wrap more_wrap\">\r\n");
      out.write("\r\n");
      out.write("	<!-- Nav -->\r\n");
      out.write("	<nav>\r\n");
      out.write("    <ul>\r\n");
      out.write("        <li><a href=\"/more/faq\">자주 묻는 질문</a></li>\r\n");
      out.write("        <li><a href=\"/more/inquiry\" class=\"active\">1:1 문의</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</nav>\r\n");
      out.write("	<div class=\"align_rt\">\r\n");
      out.write("		<!-- Inquiry -->\r\n");
      out.write("		<div class=\"inquiry\">\r\n");
      out.write("\r\n");
      out.write("			<!-- Tab -->\r\n");
      out.write("			<div class=\"tab\">\r\n");
      out.write("				<span class=\"tab_btn active\">나의 문의 내역</span>\r\n");
      out.write("				<span class=\"tab_btn \">새 문의 작성</span>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- 리스트 -->\r\n");
      out.write("			<div class=\"tab_each\" style=\"display:block\">\r\n");
      out.write("\r\n");
      out.write("									<!-- 리스트 없을때 -->\r\n");
      out.write("					<div class=\"list_none\" style=\"display: block;\">\r\n");
      out.write("						등록된 1:1 문의가 없습니다.\r\n");
      out.write("						<b>여기어때는 회원님들의 소중한 의견에 귀기울여<br>신속하고 정확하게 답변드리도록 하겠습니다.</b>\r\n");
      out.write("					</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- 작성 -->\r\n");
      out.write("			<div class=\"tab_each\">\r\n");
      out.write("				<form name=\"inq-form\" method=\"post\" action=\"/more/inquiry_submit\">\r\n");
      out.write("					<div class=\"alert_top\">\r\n");
      out.write("						<p>여기어때 이용 중 불편하신 점을 문의주시면 <em>최대한 빠른 시일내에 답변 드리겠습니다.</em></p>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<section class=\"info_wrap\">\r\n");
      out.write("						<b>카테고리유형</b>\r\n");
      out.write("						<select name=\"room_type\" id=\"\" class=\"select_type_2\">\r\n");
      out.write("							<option value=\"\">카테고리유형을 선택하세요</option>\r\n");
      out.write("															<option value=\"1\">모텔</option>\r\n");
      out.write("															<option value=\"2\">호텔·리조트</option>\r\n");
      out.write("															<option value=\"3\">펜션</option>\r\n");
      out.write("															<option value=\"6\">게스트하우스</option>\r\n");
      out.write("															<option value=\"5\">캠핑/글램핑</option>\r\n");
      out.write("															<option value=\"7\">한옥</option>\r\n");
      out.write("															<option value=\"10\">액티비티</option>\r\n");
      out.write("															<option value=\"11\">현금성(유상)포인트</option>\r\n");
      out.write("													</select>\r\n");
      out.write("\r\n");
      out.write("						<b>문의유형</b>\r\n");
      out.write("						<select name=\"inq_type\" id=\"inq_type\" class=\"select_type_2\">\r\n");
      out.write("							<option value=\"\">문의유형을 선택하세요</option>\r\n");
      out.write("															<option value=\"8\">이벤트</option>\r\n");
      out.write("															<option value=\"7\">예약/결제</option>\r\n");
      out.write("															<option value=\"9\">취소/환불</option>\r\n");
      out.write("															<option value=\"2\">혜택받기</option>\r\n");
      out.write("															<option value=\"1\">이용문의</option>\r\n");
      out.write("															<option value=\"4\">회원정보</option>\r\n");
      out.write("															<option value=\"3\">리뷰</option>\r\n");
      out.write("															<option value=\"10\">환불신청</option>\r\n");
      out.write("															<option value=\"99\">기타</option>\r\n");
      out.write("													</select>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"phone-block\">\r\n");
      out.write("							<b>휴대폰 번호</b>\r\n");
      out.write("							<p class=\"inp_wrap\"><input class=\"js-phone-number\" data-type=\"phoneNumber\" type=\"tel\" maxlength=\"11\" name=\"uphone\" value=\"\" placeholder=\"선택사항입니다.\"><button type=\"button\" class=\"reset_val\">초기화</button></p>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"email-block\">\r\n");
      out.write("							<b>이메일</b>\r\n");
      out.write("							<p class=\"inp_wrap\"><input data-email-validate=\"\" class=\"js-email-string\" type=\"email\" value=\"\" name=\"uemail\" placeholder=\"선택사항입니다.\"><button type=\"button\" class=\"reset_val\">초기화</button></p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</section>\r\n");
      out.write("\r\n");
      out.write("					<section class=\"text_wrap\">\r\n");
      out.write("						<b>문의내용</b>\r\n");
      out.write("						<div>\r\n");
      out.write("							<textarea name=\"content\" id=\"questionTextarea\"></textarea>\r\n");
      out.write("							<ul class=\"placeholder_txt\">\r\n");
      out.write("								<li>문의하실 내용을 10자 이상 입력해 주세요.</li>\r\n");
      out.write("								<li>문의하시는 제휴점 이름과 예약정보를 남겨주시면 보다 빠른 상담이 가능합니다.</li>\r\n");
      out.write("								<li>문의 내용 작성 시 개인정보가 입력되지 않도록 주의 부탁드립니다.</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</section>\r\n");
      out.write("\r\n");
      out.write("					<section class=\"agree_wrap\">\r\n");
      out.write("						<div>\r\n");
      out.write("							<input type=\"checkbox\" id=\"info_agree\" name=\"checkOne\" class=\"inp_chk_04\" disabled=\"\">\r\n");
      out.write("							<label for=\"info_agree\">개인정보수집. 이용동의</label>\r\n");
      out.write("							<btn class=\"view_contents\">[내용보기]</btn>\r\n");
      out.write("						</div>\r\n");
      out.write("					</section>\r\n");
      out.write("\r\n");
      out.write("					<section class=\"btn_wrap \">\r\n");
      out.write("						<button class=\"btn_red_fill\" type=\"button\" onclick=\"$.inqSubmit();\">작성 완료</button>\r\n");
      out.write("					</section>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- 개인정보처리방침동의 팝업 -->\r\n");
      out.write("			<div class=\"box_shadow\" id=\"common_popup_agree\">\r\n");
      out.write("				<div class=\"msg popup_cont\">\r\n");
      out.write("					<div class=\"text\">\r\n");
      out.write("						<div><strong class=\"privacy_title\">개인정보 수집·이용 동의하십니까? </strong></div>\r\n");
      out.write("						<div class=\"privacy-bill\">\r\n");
      out.write("							<p>(주)여기어때컴퍼니는 ‘유선답변 및 이메일 답변'을 희망하는 이용자를 대상으로 아래와 같이 개인정보를 수집하고 있습니다. 개인정보 수집/이용에 대한 내용을 확인하고, 동의 여부를 결정하여 주시기 바랍니다.</p>\r\n");
      out.write("							<br>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li>1. 수집 개인정보 항목 : (선택) 휴대전화번호, 이메일</li>\r\n");
      out.write("								<li>2. 수집 및 이용 목적 : 고객상담 및 정보제공</li>\r\n");
      out.write("								<li>3. 보유 및 이용기간 : <b>상담완료 후 3년</b></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("							<br>\r\n");
      out.write("							동의를 원하지 않는 경우 수집/이용 동의를 거부할 수 있으며, 동의 거부시에도 1:1 문의 서비스를 이용할 수 있습니다. 다만, ‘유선 및 이메일 답변’ 서비스는 불가함을 알려드립니다.<br>\r\n");
      out.write("							위 내용을 포함하여 개인정보 관련 상세사항은 <strong>'개인정보 처리방침'</strong>을 준수하고 있습니다.\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"btns-wrap\">\r\n");
      out.write("						<button class=\"btn disagree\">닫기</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!--// 개인정보처리방침동의 팝업 -->\r\n");
      out.write("\r\n");
      out.write("			<!-- 개인정보처리방침동의 팝업2 -->\r\n");
      out.write("			<div class=\"box_shadow\" id=\"common_popup_agree2\">\r\n");
      out.write("				<div class=\"msg popup_cont\">\r\n");
      out.write("					<div class=\"text\">\r\n");
      out.write("						<div class=\"privacy-bill\">\r\n");
      out.write("							작성하신 문의를 여기어때 고객행복센터로<br>\r\n");
      out.write("							보내시겠습니까?\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"btns-wrap\">\r\n");
      out.write("						<button class=\"btn disagree2\">취소</button>\r\n");
      out.write("						<button class=\"btn send-form\" data-type=\"privacyAgree\">보내기</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!--// 개인정보처리방침동의 팝업2 -->\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- //Notice -->\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //Content  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"align\">\r\n");
      out.write("            <ul class=\"link\">\r\n");
      out.write("                <li><a href=\"http://www.withinnovation.co.kr/\" target=\"_blank\">회사소개</a><span>|</span></li>\r\n");
      out.write("                <li><a href=\"https://www.goodchoice.kr/more/terms\" data-default=\"term\">이용약관</a><span>|</span></li>\r\n");
      out.write("                <li><a href=\"https://www.goodchoice.kr/more/terms/privacy\" data-default=\"privacy\">개인정보처리방침</a><span>|</span></li>\r\n");
      out.write("                <li><a href=\"https://www.goodchoice.kr/more/terms/consumer\" data-default=\"consumer\">소비자 분쟁해결 기준</a><span>|</span></li>\r\n");
      out.write("                <li><button type=\"button\" onclick=\"pop_licence();return false;\">사업자 정보확인</button><span>|</span></li>\r\n");
      out.write("                <li><a href=\"//ad.goodchoice.kr/\" target=\"_blank\">여기어때 마케팅센터</a><span>|</span></li>\r\n");
      out.write("                <li><a href=\"//host.goodchoice.kr/\" target=\"_blank\">액티비티 호스트센터</a><span>|</span></li>\r\n");
      out.write("                <li><a href=\"//hotel.goodchoice.kr/\" target=\"_blank\">HOTEL 여기어때</a><span>|</span></li>\r\n");
      out.write("                <li><a href=\"https://www.goodchoice.kr/more/contentsInfo\">콘텐츠산업진흥법에의한 표시</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <p><b>고객행복센터 1670-6250</b><span>오전 9시 - 새벽 3시</span></p>\r\n");
      out.write("            <address>\r\n");
      out.write("                <span>(주) 여기어때컴퍼니</span>\r\n");
      out.write("								주소 : 서울특별시 강남구 봉은사로 479, 479타워 11층 | 대표이사 : 정명훈 | 사업자등록번호: 742-86-00224 | 전자우편주소 : help@goodchoice.kr<br>\r\n");
      out.write("                통신판매번호 : 2017-서울강남-01779 | 관광사업자 등록번호: 제1026-24호 | 전화번호 : 1670-6250 | 호스팅서비스제공자의 상호 표시: (주)여기어때컴퍼니<br>\r\n");
      out.write("                <span class=\"order\">(주) 여기어때컴퍼니는 통신판매중개자로서 통신판매의 당사자가 아니며, 상품의 예약, 이용 및 환불 등과 관련한 의무와 책임은 각 판매자에게 있습니다.</span><br>\r\n");
      out.write("                Copyright GC COMPANY Corp. All rights reserved.\r\n");
      out.write("            </address>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"ico\">\r\n");
      out.write("                <a href=\"//www.facebook.com/goodchoiceofficial\" target=\"_black\" class=\"icon-icn_login_facebook\"><span>여기어때 페이스북</span></a>\r\n");
      out.write("                <a href=\"//blog.gccompany.co.kr\" target=\"_black\" class=\"icon-ic_blog\"><span>여기어때 블로그</span></a>\r\n");
      out.write("                <a href=\"//post.naver.com/my.nhn?memberNo=25599212\" target=\"_black\" class=\"icon-ic_naverpost\"><span>네이버포스트</span></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("	<!-- 상단으로 -->\r\n");
      out.write("	<button class=\"btn_go_top\" onclick=\"moveTop();\" style=\"display: none;\">상단으로</button>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
