/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-24 03:55:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.inquiry;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class FAQ_002dTOP7_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>자주 묻는 질문</title>\r\n");
      out.write("<link href=\"../../static/css/inquiry/FAQ.css\" rel=\"stylesheet\"\r\n");
      out.write("	type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"wrap show\">\r\n");
      out.write("		<!-- Header -->\r\n");
      out.write("		<header id=\"menu\">\r\n");
      out.write("			<section>\r\n");
      out.write("				<div>\r\n");
      out.write("					<img\r\n");
      out.write("						style=\"width: 150px; height: 150px; margin-left: -90px; margin-top: -33px;\"\r\n");
      out.write("						src=\"../../static/image/logo.png\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<h1>\r\n");
      out.write("					<a href=\"\" id=\"bannertext\">Save The Animal Relationship</a>\r\n");
      out.write("				</h1>\r\n");
      out.write("				<button type=\"button\" class=\"btn_srch srch_open\">검색</button>\r\n");
      out.write("				<ul class=\"gnb_pc\">\r\n");
      out.write("					<li><a class=\"bannertext\" href=\"\">내주변</a></li>\r\n");
      out.write("					<li><a class=\"bannertext\" href=\"\">예약내역</a></li>\r\n");
      out.write("					<li><a class=\"bannertext\" href=\"\">더보기</a></li>\r\n");
      out.write("					<li><a class=\"bannertext\" href=\"\">로그인</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</section>\r\n");
      out.write("		</header>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Sub Top -->\r\n");
      out.write("	<div class=\"sub_top_wrap\">\r\n");
      out.write("		<div class=\"sub_top bg_kong_3\">\r\n");
      out.write("			<h2>더보기</h2>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- //Sub Top -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div id=\"content\" class=\"sub_wrap more_wrap\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Nav -->\r\n");
      out.write("		<nav>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"../inquiry/FAQ-TOP7.jsp\" class=\"active\">자주 묻는\r\n");
      out.write("						질문</a></li>\r\n");
      out.write("				<li><a href=\"../inquiry/OTOlist.jsp\">서비스 문의</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<div class=\"align_rt\">\r\n");
      out.write("\r\n");
      out.write("			<!-- Faq -->\r\n");
      out.write("			<div class=\"faq\">\r\n");
      out.write("\r\n");
      out.write("				<!-- 상단 탭 버튼 -->\r\n");
      out.write("				<div class=\"top_link\">\r\n");
      out.write("					<li><a href=\"../inquiry/FAQ-TOP7.jsp\" class=\"on\">TOP7</a></li>\r\n");
      out.write("					<li><a href=\"../inquiry/M1.jsp\" class=\"\">M1</a></li>\r\n");
      out.write("					<li><a href=\"../inquiry/M2.jsp\" class=\"\">M2</a></li>\r\n");
      out.write("					<li><a href=\"../inquiry/M3.jsp\" class=\"\">M3</a></li>\r\n");
      out.write("					<li><a href=\"../inquiry/M4.jsp\" class=\"\">M4</a></li>\r\n");
      out.write("					<li><a href=\"../inquiry/M5.jsp\" class=\"\">M5</a></li>\r\n");
      out.write("					<li><a href=\"../inquiry/M6.jsp\" class=\"\">M6</a></li>\r\n");
      out.write("					<li><a href=\"../inquiry/M7.jsp\" class=\"\">M7</a></li>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- //상단 탭 버튼 -->\r\n");
      out.write("\r\n");
      out.write("				<!-- List -->\r\n");
      out.write("				<div class=\"faq_list\">\r\n");
      out.write("					<strong class=\"title\">자주 묻는 질문</strong>\r\n");
      out.write("					<div class=\"list\" style=\"display: block\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li>\r\n");
      out.write("								<p class=\"link\">\r\n");
      out.write("									<span>[예약] 예약을 취소하고 싶어요.</span>\r\n");
      out.write("								</p>\r\n");
      out.write("								<div class=\"ans\">\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">예약취소는&nbsp; 앱/웹 &gt; 내정보\r\n");
      out.write("												&gt; 예약/구매내역에서 직접 가능합니다.</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\"><br></span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">예약/결제 진행 당시 안내된 취소/환불\r\n");
      out.write("												규정에 따라 처리되며, 취소수수료가 발생할 경우 취소수수료를 차감한 금액으로 환불 처리됩니다.</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">일부 숙소에 한해 취소가 가능한 시점이나\r\n");
      out.write("												앱/웹에서 취소가 불가할 수 있으니 이 경우에는 고객행복센터로 요청해 주시길 바랍니다.</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li>\r\n");
      out.write("								<p class=\"link\">\r\n");
      out.write("									<span>[예약취소] 천재지변/감염병으로 인한 예약취소는 어떻게 하나요?</span>\r\n");
      out.write("								</p>\r\n");
      out.write("								<div class=\"ans\">\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">천재지변(기상악화), 법정 감염병 등\r\n");
      out.write("												불가항력적인 사유로 제휴점 이용이 불가할 경우 고객행복센터로 예약내역 및 증빙서류(결항확인서, e-티켓,\r\n");
      out.write("												진단확인서 등)를 보내주시면 확인 후 예약취소 가능 여부를 확인해 드립니다.</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\"><br></span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">다만, 당사는 판매 중개 플랫폼의 입장으로\r\n");
      out.write("												제휴점에 대하여 취소/환불을 강제할 수 없어 각 제휴점의 규정에 근거하여 상황에 따라 수수료가 발생하거나\r\n");
      out.write("												취소가 어려울 수 있는 점 양해 부탁드립니다.</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\"><br></span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\"><b>[접수방법]</b></span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">※ 이메일 :\r\n");
      out.write("												help@goodchoice.kr (예약자명, 숙소명, 체크인 날짜 필수)</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">※ 카카오톡 : 카카오톡 내 플러스 친구\r\n");
      out.write("												&gt; 여기어때 고객행복센터 추가</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li>\r\n");
      out.write("								<p class=\"link\">\r\n");
      out.write("									<span>[지역설정] 동네만 선택할 수 있나요?</span>\r\n");
      out.write("								</p>\r\n");
      out.write("								<div class=\"ans\">\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">예약 대기중에는 여기어때 고객행복센터에\r\n");
      out.write("												예약취소 요청해주시길 바랍니다.</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\"><br></span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">단, 예약확정이 될 경우 수수료가 발생하거나\r\n");
      out.write("												예약취소가 불가할 수 있습니다.</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li>\r\n");
      out.write("								<p class=\"link\">\r\n");
      out.write("									<span>[회원가입] 개명해서 이름변경하고 싶어요.</span>\r\n");
      out.write("								</p>\r\n");
      out.write("								<div class=\"ans\">\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">예약 결제 완료 후 날짜 및 객실타입 등\r\n");
      out.write("												부분 변경은 불가합니다.</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\"><br></span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">예약취소와 동일하게 취소 및 환불 규정에\r\n");
      out.write("												따라 처리되므로 예약취소가 가능한 기간에는 예약취소 후 재결제 하셔서 이용 부탁드립니다.</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\"><br></span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">만약, 예약취소가 불가하거나 수수료가\r\n");
      out.write("												발생하는 경우라면 고객행복센터로 문의해주시길 바랍니다.</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li>\r\n");
      out.write("								<p class=\"link\">\r\n");
      out.write("									<span>[이용내역] 3년전 기록을 보고 싶어요.</span>\r\n");
      out.write("								</p>\r\n");
      out.write("								<div class=\"ans\">\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">현금영수증은 현금성 결제수단으로 결제 시\r\n");
      out.write("												발급이 가능합니다.</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\"><br></span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">결제 단계에서 현금영수증을 신청하면 자동으로\r\n");
      out.write("												발행되지만,</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">신청을 누락했거나 발행받지 못한 경우라면\r\n");
      out.write("												영수증 확인 후 국세청에서 자진발급분을 등록해 주시길 바랍니다.</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\"><br></span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">[네이버페이]</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">- 결제 단계에서 현금영수증 신청하면\r\n");
      out.write("												자동으로 발행 (19년 12월 26일 시행)</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">- 자진발급 : 네이버페이 &gt; 결제내역\r\n");
      out.write("												&gt; 주문건 &gt; 주문상세정보 &gt; 영수증 발급내역 &gt; 현금영수증 확인</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">- 단, 19년 12월 26일 10시 이전\r\n");
      out.write("												결제 건은 여기어때 고객행복센터로 요청</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\"><br></span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">[간편계좌이체 / TOSS / PAYCO]</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">- 결제 단계에서 현금영수증 신청하면\r\n");
      out.write("												자동으로 발행</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">- 단, 간편계좌이체의 경우 신청 누락 시\r\n");
      out.write("												여기어때 고객행복센터로 요청</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\"><br></span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">[카카오페이]&nbsp;</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">- 카카오페이머니 결제 시 자동으로 발행</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">- 자진발급 : 카카오톡 &gt; pay\r\n");
      out.write("												&gt; 우측톱니바퀴(나의 카카오페이) &gt; 이용내역 &gt; 결제 &gt; 개별 상세내역 &gt;\r\n");
      out.write("												현금영수증 확인</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li>\r\n");
      out.write("								<p class=\"link\">\r\n");
      out.write("									<span>[공통] 공통 문의 넣기</span>\r\n");
      out.write("								</p>\r\n");
      out.write("								<div class=\"ans\">\r\n");
      out.write("									<p>\r\n");
      out.write("										<font face=\"Arial\"><span\r\n");
      out.write("											style=\"font-size: 13px; white-space: pre-wrap;\">예약정보와\r\n");
      out.write("												결제정보가 기재되어 있는 영수증(거래내역서)은 여기어때 고객행복센터로 문의하시면 발급이 가능합니다.\r\n");
      out.write("\r\n");
      out.write("												예약내역, 영수증을 받으실 이메일 주소(또는 FAX번호)를 1:1문의 또는 카카오 상담톡으로 남겨주시길\r\n");
      out.write("												바라며, 발급 완료까지는 영업일 기준 최대 1~2일 소요되오니 시간 양해 부탁드립니다.</span></font>\r\n");
      out.write("									</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li>\r\n");
      out.write("								<p class=\"link\">\r\n");
      out.write("									<span>[공통] 공통 문의 넣기</span>\r\n");
      out.write("								</p>\r\n");
      out.write("								<div class=\"ans\">\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">엘리트는 여기어때를 통해 국내\r\n");
      out.write("												숙소/모바일티켓 상관없이 실 결제금액 3만원 이상 예약한 경우에만 적용되며 숙소는 체크아웃(퇴실),\r\n");
      out.write("												모바일티켓은 이용 완료 후 자동 적립됩니다.</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\"><br></span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">쿠폰/포인트 사용 후 실 결제금액이 3만원\r\n");
      out.write("												미만일 경우 적립이 불가하오니 결제금액을 확인해주시길 바랍니다.</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<font color=\"#252525\" face=\"arial\"><span\r\n");
      out.write("											style=\"font-size: 13.3333px;\">공간대여/실시간 렌터카/해외 숙소 상품은\r\n");
      out.write("												엘리트 적립에서 제외됩니다.</span></font>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- //List -->\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- //Faq -->\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("	<footer>\r\n");
      out.write("		<div class=\"align\">\r\n");
      out.write("			<ul class=\"link\">\r\n");
      out.write("				<li><a href=\"http://www.naver.com/\" target=\"_blank\">회사소개</a><span>|</span></li>\r\n");
      out.write("				<li><a href=\"http://www.naver.com/\" data-default=\"term\">이용약관</a><span>|</span></li>\r\n");
      out.write("				<li><a href=\"http://www.naver.com/\" data-default=\"privacy\">개인정보처리방침</a><span>|</span></li>\r\n");
      out.write("				<li><a href=\"http://www.naver.com/\" target=\"_blank\">돌봄예약신청</a><span>|</span></li>\r\n");
      out.write("				<li><a href=\"http://www.naver.com/\" target=\"_blank\">돌봄이용후기</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<p>\r\n");
      out.write("				<b>고객센터 1588-5890</b><span>오전 9시 - 오후 6시</span>\r\n");
      out.write("			</p>\r\n");
      out.write("			<address>\r\n");
      out.write("				<span>(주) STAR컴퍼니</span> 주소 : 서울 강남구 테헤란로 146 | 대표이사 : STAR |\r\n");
      out.write("				사업자등록번호: 010-12-34567 | 전자우편주소 : star@star.kr<br> 통신판매번호 :\r\n");
      out.write("				2023-서울강남-01001 | 관광사업자 등록번호: 제2023-01호 | 전화번호 : 1588-5890 |\r\n");
      out.write("				호스팅서비스제공자의 상호 표시: (주) STAR컴퍼니<br> <span class=\"order\">(주)\r\n");
      out.write("					STAR컴퍼니는 서비스예약중개자로서 서비스제공의 당사자가 아니며, 서비스의 예약, 이용과 관련한 의무와 책임은 각\r\n");
      out.write("					이용자에게 있습니다.</span><br> Copyright STAR COMPANY Corp. All rights\r\n");
      out.write("				reserved.\r\n");
      out.write("			</address>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("	<!-- 상단으로 -->\r\n");
      out.write("	<button class=\"btn_go_top\" onclick=\"moveTop();\" style=\"display: none;\">상단으로</button>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.4.min.js\"></script>\r\n");
      out.write("<script src=\"../../static/js/inquiry/FAQ.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
