/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-26 07:21:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.sitter;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../static/css/sitter/view.css\">\r\n");
      out.write("    <title>돌봄이 상세보기</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"pc\">\r\n");
      out.write("    <div class=\"wrap show\">\r\n");
      out.write("	<header id=\"menu\">\r\n");
      out.write("        <section>\r\n");
      out.write("            <div>\r\n");
      out.write("			<div>\r\n");
      out.write("                <img style=\"width: 150px; height: 150px; margin-left: -90px; margin-top: -33px;\" src=\"../../static/image/3.png\">\r\n");
      out.write("                </div>\r\n");
      out.write("            <h1>                 \r\n");
      out.write("                <a href=\"../../templates/mainpage.jsp\" id=\"bannertext\">Save The Animal Relationship</a>\r\n");
      out.write("            </h1>\r\n");
      out.write("            <ul class=\"gnb_pc\" >\r\n");
      out.write("                <li><a class=\"bannertext\" href=\"\">내주변</a></li>\r\n");
      out.write("                <li><a class=\"bannertext\" href=\"\">예약내역</a></li>\r\n");
      out.write("                <li><a class=\"bannertext\" href=\"\">더보기</a></li>\r\n");
      out.write("                <li><a class=\"bannertext\" href=\"\">로그인</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </section>\r\n");
      out.write("   	 </header>\r\n");
      out.write("        <form id=\"product_filter_form\" method=\"get\">\r\n");
      out.write("            <div class=\"listpage\">\r\n");
      out.write("                <div class=\"sub_top_wrap\">\r\n");
      out.write("                    <div class=\"sub_top bg_kong_1\">\r\n");
      out.write("                        <h2>돌봄이 상세보기</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        <div id=\"content\" class=\"detail \">\r\n");
      out.write("            <div class=\"top\">\r\n");
      out.write("                <div class=\"left\">\r\n");
      out.write("                    <div class=\"gallery_pc\">\r\n");
      out.write("                        <div class=\"swiper-container gallery-top swiper-container-horizontal swiper-container-fade\">\r\n");
      out.write("                            <ul class=\"swiper-wrapper\" style=\"transition-duration: 0ms;\">\r\n");
      out.write("                                <li class=\"swiper-slide swiper-slide-active\">\r\n");
      out.write("                                    <!-- <img src=\"https://wimg.mk.co.kr/meet/neds/2017/05/image_readtop_2017_303044_14939955542872338.jpg\" class=\"swiper-lazy swiper-lazy-loaded\"> -->\r\n");
      out.write("                                    <img src=\"https://www.bsbukgu.go.kr/upload_data/board_data/NEWS/157502695976272.png\" class=\"swiper-lazy swiper-lazy-loaded\">\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"right\">\r\n");
      out.write("                    <div class=\"info\">\r\n");
      out.write("                        <p class=\"badge\">\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <h2>강형욱 돌봄이</h2>\r\n");
      out.write("                        <div class=\"score_cnt\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"address\">#돌봄이 이수증 #반려견 훈련 강사 #행동 상담 전문</p>\r\n");
      out.write("                        <div class=\"benefit_wrap\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"comment\">\r\n");
      out.write("                        <strong>돌봄이 자기소개</strong>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"\">지금 우리의 옆에 같이 있는 가족 반려견 우리 아이들에 대해 얼마나 알고 계신가요? 서로를 위해 우리 아이들은 우리들의 옆에 정말 가까이 있습니다.\r\n");
      out.write("                            가까이 있으면서 문제가 생기기는 일은 당연한 일입니다. 가까운 사이 일수록 더욱 지치기도 쉽고 다투기도 잦습니다. 저는 우리 아이들에게 그리고 보호자님에게 서로의\r\n");
      out.write("                            마음으로 하는 소통의 창을 열어드리고자 합니다. </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div style=\"margin:39px;padding-bottom:32px;border-bottom:1px solid #EBEBEB\">\r\n");
      out.write("                <div style=\"display:flex;flex-direction:row;margin-top:27px\">\r\n");
      out.write("                    <img src=\"https://wayopet.com/static/images/trainer_detail/img_career_1.png\" style=\"width:32px;height:32px\">\r\n");
      out.write("                    <div style=\"margin-top:4px;margin-left:18px\">\r\n");
      out.write("                        <p style=\"font-weight:500;font-size:17px;color:#333333;letter-spacing:-0.2px\">대표 경력</p><p style=\"font-size:15px;color:#777777;line-height:20px;margin-top:10px\">방문훈련 전문, 동물병원근무, 행동교정 전문</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"display:flex;flex-direction:row;margin-top:27px\">\r\n");
      out.write("                    <img src=\"https://wayopet.com/static/images/trainer_detail/img_career_2.png\" style=\"width:32px;height:32px\">\r\n");
      out.write("                    <div style=\"margin-top:4px;margin-left:18px\">\r\n");
      out.write("                        <p style=\"font-weight:500;font-size:17px;color:#333333;letter-spacing:-0.2px\">전문 분야</p>\r\n");
      out.write("                        <p style=\"font-size:15px;color:#777777;line-height:20px;margin-top:10px\">공격성 교육 전문, 소/중형견 전문</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"display:flex;flex-direction:row;margin-top:27px\">\r\n");
      out.write("                    <img src=\"	https://wayopet.com/static/images/trainer_detail/img_career_3.png\" style=\"width:32px;height:32px\">\r\n");
      out.write("                    <div style=\"margin-top:4px;margin-left:18px\">\r\n");
      out.write("                        <p style=\"font-weight:500;font-size:17px;color:#333333;letter-spacing:-0.2px\">방문 지역</p>\r\n");
      out.write("                        <p style=\"font-size:15px;color:#777777;line-height:20px;margin-top:10px\"> 강남구, 서초구, 동대문구, 의정부시 , 성남시, 용인시, 시흥시</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"margin-top: 42px;\">\r\n");
      out.write("                    <h2\r\n");
      out.write("                        style=\"font-weight: 600; font-size: 17px; letter-spacing: -0.2px; line-height: 25px; color: rgb(57, 60, 71); margin-bottom: 24px;\">\r\n");
      out.write("                        놀이 서비스</h2>\r\n");
      out.write("                    <div style=\"display: flex; flex-flow: row wrap;\">\r\n");
      out.write("                        <div\r\n");
      out.write("                            style=\"display: flex; flex-direction: row; align-items: center; width: 200px; height: 69px;\">\r\n");
      out.write("                            <img width=\"32\" height=\"32\"\r\n");
      out.write("                                src=\"https://petplanet.co/static/images/page_details/services/image8.png\">\r\n");
      out.write("                            <div style=\"margin-left: 13px;\">\r\n");
      out.write("                                <p\r\n");
      out.write("                                    style=\"font-size: 13px; letter-spacing: -0.2px; line-height: 19px; color: rgb(85, 85, 85);\">\r\n");
      out.write("                                    공놀이</p>\r\n");
      out.write("                                <p\r\n");
      out.write("                                    style=\"font-size: 11px; letter-spacing: -0.2px; line-height: 17px; color: rgb(94, 99, 109); margin-top: 5px;\">\r\n");
      out.write("                                    공놀이</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div\r\n");
      out.write("                            style=\"display: flex; flex-direction: row; align-items: center; width: 200px; height: 69px;\">\r\n");
      out.write("                            <img width=\"32\" height=\"32\"\r\n");
      out.write("                                src=\"https://petplanet.co/static/images/page_details/services/image8.png\">\r\n");
      out.write("                            <div style=\"margin-left: 13px;\">\r\n");
      out.write("                                <p\r\n");
      out.write("                                    style=\"font-size: 13px; letter-spacing: -0.2px; line-height: 19px; color: rgb(85, 85, 85);\">\r\n");
      out.write("                                    프리스비</p>\r\n");
      out.write("                                <p\r\n");
      out.write("                                    style=\"font-size: 11px; letter-spacing: -0.2px; line-height: 17px; color: rgb(94, 99, 109); margin-top: 5px;\">\r\n");
      out.write("                                    원반 놀이</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div\r\n");
      out.write("                            style=\"display: flex; flex-direction: row; align-items: center; width: 200px; height: 69px;\">\r\n");
      out.write("                            <img width=\"32\" height=\"32\"\r\n");
      out.write("                                src=\"https://petplanet.co/static/images/page_details/services/image8.png\">\r\n");
      out.write("                            <div style=\"margin-left: 13px;\">\r\n");
      out.write("                                <p\r\n");
      out.write("                                    style=\"font-size: 13px; letter-spacing: -0.2px; line-height: 19px; color: rgb(85, 85, 85);\">\r\n");
      out.write("                                    술래잡기</p>\r\n");
      out.write("                                <p\r\n");
      out.write("                                    style=\"font-size: 11px; letter-spacing: -0.2px; line-height: 17px; color: rgb(94, 99, 109); margin-top: 5px;\">\r\n");
      out.write("                                    술래잡기 놀이</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div\r\n");
      out.write("                            style=\"display: flex; flex-direction: row; align-items: center; width: 200px; height: 69px;\">\r\n");
      out.write("                            <img width=\"32\" height=\"32\"\r\n");
      out.write("                                src=\"https://petplanet.co/static/images/page_details/services/image8.png\">\r\n");
      out.write("                            <div style=\"margin-left: 13px;\">\r\n");
      out.write("                                <p\r\n");
      out.write("                                    style=\"font-size: 13px; letter-spacing: -0.2px; line-height: 19px; color: rgb(85, 85, 85);\">\r\n");
      out.write("                                    치실토이</p>\r\n");
      out.write("                                <p\r\n");
      out.write("                                    style=\"font-size: 11px; letter-spacing: -0.2px; line-height: 17px; color: rgb(94, 99, 109); margin-top: 5px;\">\r\n");
      out.write("                                    치실토이 놀이</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div\r\n");
      out.write("                            style=\"display: flex; flex-direction: row; align-items: center; width: 200px; height: 69px;\">\r\n");
      out.write("                            <img width=\"32\" height=\"32\"\r\n");
      out.write("                                src=\"https://petplanet.co/static/images/page_details/services/image8.png\">\r\n");
      out.write("                            <div style=\"margin-left: 13px;\">\r\n");
      out.write("                                <p\r\n");
      out.write("                                    style=\"font-size: 13px; letter-spacing: -0.2px; line-height: 19px; color: rgb(85, 85, 85);\">\r\n");
      out.write("                                    노즈워크</p>\r\n");
      out.write("                                <p\r\n");
      out.write("                                    style=\"font-size: 11px; letter-spacing: -0.2px; line-height: 17px; color: rgb(94, 99, 109); margin-top: 5px;\">\r\n");
      out.write("                                    후각을 자극하는 실내놀이</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div\r\n");
      out.write("                            style=\"display: flex; flex-direction: row; align-items: center; width: 200px; height: 69px;\">\r\n");
      out.write("                            <img width=\"32\" height=\"32\"\r\n");
      out.write("                                src=\"https://petplanet.co/static/images/page_details/services/image8.png\">\r\n");
      out.write("                            <div style=\"margin-left: 13px;\">\r\n");
      out.write("                                <p\r\n");
      out.write("                                    style=\"font-size: 13px; letter-spacing: -0.2px; line-height: 19px; color: rgb(85, 85, 85);\">\r\n");
      out.write("                                    컵 놀이</p>\r\n");
      out.write("                                <p\r\n");
      out.write("                                    style=\"font-size: 11px; letter-spacing: -0.2px; line-height: 17px; color: rgb(94, 99, 109); margin-top: 5px;\">\r\n");
      out.write("                                    집중력과 두뇌 자극 놀이</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- footer 임시 -->\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"align\">\r\n");
      out.write("            <ul class=\"link\">\r\n");
      out.write("                <li><a href=\"\">서비스문의</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <p><b>고객행복센터 1670-6250</b><span>오전 9시 - 새벽 3시</span></p>\r\n");
      out.write("            <address>\r\n");
      out.write("                <span>(주) STAR</span>\r\n");
      out.write("                주소 : 서울특별시 강남구 봉은사로 479, 479타워 11층 | 대표이사 : 정명훈 | 사업자등록번호: 742-86-00224 | 전자우편주소 :\r\n");
      out.write("                help@goodchoice.kr<br>\r\n");
      out.write("                통신판매번호 : 2017-서울강남-01779 | 관광사업자 등록번호: 제1026-24호 | 전화번호 : 1670-6250 | 호스팅서비스제공자의 상호 표시: (주)여기어때컴퍼니<br>\r\n");
      out.write("                <span class=\"order\">(주) 여기어때컴퍼니는 통신판매중개자로서 통신판매의 당사자가 아니며, 상품의 예약, 이용 및 환불 등과 관련한 의무와 책임은 각 판매자에게\r\n");
      out.write("                    있습니다.</span><br>\r\n");
      out.write("                Copyright GC COMPANY Corp. All rights reserved.\r\n");
      out.write("            </address>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("const menu = document.querySelector('#menu');\r\n");
      out.write("const bannertext = document.querySelector('#bannertext');\r\n");
      out.write("const banner = document.querySelectorAll('.bannertext');\r\n");
      out.write("const menuHeight = menu.getBoundingClientRect().height;\r\n");
      out.write("\r\n");
      out.write("document.addEventListener('scroll', () => {\r\n");
      out.write("\r\n");
      out.write("  if (window.scrollY > menuHeight) {\r\n");
      out.write("    menu.classList.add('active');\r\n");
      out.write("    bannertext.classList.add('textactive2');\r\n");
      out.write("    for(let i=0; i<banner.length; i++){\r\n");
      out.write("        banner[i].classList.add('textactive');\r\n");
      out.write("    }\r\n");
      out.write("  } else {\r\n");
      out.write("    menu.classList.remove('active');\r\n");
      out.write("    bannertext.classList.remove('textactive2');\r\n");
      out.write("    for(let i=0; i<banner.length; i++){\r\n");
      out.write("        banner[i].classList.remove('textactive');\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
