/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-26 07:19:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../../static/css/mypage/joinout.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css\" />\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"withdraw_popup_container\">\r\n");
      out.write("		<div class=\"withdraw_popup\">\r\n");
      out.write("			<div class=\"withdraw_popup__header\">\r\n");
      out.write("				<div class=\"withdraw_title\">\r\n");
      out.write("					<p>회원탈퇴</p>\r\n");
      out.write("					<svg width=\"20\" height=\"20\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\" data-v-5a4f86fc class>\r\n");
      out.write("					<path d=\"M10 8.586l5.657-5.657 1.414 1.414L11.414 10l5.657 5.657-1.414 1.414L10 11.414l-5.657 5.657-1.414-1.414L8.586 10 2.929 4.343 4.343 2.93 10 8.586z\" fill=\"#000\" fill-opacity=\".8\" data-v-5a4f86fc></path>\r\n");
      out.write("					</svg>\r\n");
      out.write("					<svg></svg>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"withdraw_popup__content\">\r\n");
      out.write("				<div class=\"withdraw-survey-container\">\r\n");
      out.write("					<div class=\"withdraw-survey-title\">\r\n");
      out.write("						<span>왜 떠나시는지</span>\r\n");
      out.write("						<span>\r\n");
      out.write("							<span class=\"emphasis\">이유</span>가 있을까요?\r\n");
      out.write("						</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<ul class=\"radio-list\">\r\n");
      out.write("						<li class=\"radio-list__item\">\r\n");
      out.write("							<div class=\"select-item-area\">\r\n");
      out.write("								<div style=\"display: inline-block;vertical-align: text-top;width: 20px;height: 20px;overflow: hidden;margin-right: 12px;\">\r\n");
      out.write("									<input type=\"checkbox\">\r\n");
      out.write("									<!-- <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 60 60\" width=\"60\" height=\"60\" preserveAspectRatio=\"xMidYMid meet\" style=\"width: 100%; height: 100%; transform: translate3d(0px, 0px, 0px); content-visibility: visible;\">\r\n");
      out.write("										<defs>\r\n");
      out.write("											<clipPath id=\"__lottie_element_2\">\r\n");
      out.write("												<rect width=\"60\" height=\"60\" x=\"0\" y=\"0\"></rect>\r\n");
      out.write("											</clipPath>\r\n");
      out.write("										</defs>\r\n");
      out.write("										<g clip-path=\"url(#__lottie_element_2)\">\r\n");
      out.write("											<g transform=\"matrix(0.9800000190734863,0,0,0.9800000190734863,30,30)\" opacity=\"1\" style=\"display: block;\">\r\n");
      out.write("												<g opacity=\"1\" transform=\"matrix(3,0,0,3,0,0)\">\r\n");
      out.write("													 <path id=\"path\" fill=\"rgb(0,0,0)\" fill-opacity=\"0.48\" d=\" M0,8.550000190734863 C-4.71999979019165,8.550000190734863 -8.550000190734863,4.71999979019165 -8.550000190734863,0 C-8.550000190734863,-4.71999979019165 -4.71999979019165,-8.550000190734863 0,-8.550000190734863 C4.71999979019165,-8.550000190734863 8.550000190734863,-4.71999979019165 8.550000190734863,0 C8.550000190734863,4.71999979019165 4.71999979019165,8.550000190734863 0,8.550000190734863z M0,9.5 C5.25,9.5 9.5,5.25 9.5,0 C9.5,-5.25 5.25,-9.5 0,-9.5 C-5.25,-9.5 -9.5,-5.25 -9.5,0 C-9.5,5.25 -5.25,9.5 0,9.5z\"></path>\r\n");
      out.write("												</g>\r\n");
      out.write("											</g>\r\n");
      out.write("										</g>\r\n");
      out.write("									</svg> -->\r\n");
      out.write("								</div>\r\n");
      out.write("								<span>사용을 잘 안하게 돼요</span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"radio-list__item\">\r\n");
      out.write("							<div class=\"select-item-area\">\r\n");
      out.write("								<div style=\"display: inline-block;vertical-align: text-top;width: 20px;height: 20px;overflow: hidden;margin-right: 12px;\">\r\n");
      out.write("									<input type=\"checkbox\">\r\n");
      out.write("									<!-- <svg id=\"click\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 60 60\" width=\"60\" height=\"60\" preserveAspectRatio=\"xMidYMid meet\" style=\"width: 100%; height: 100%; transform: translate3d(0px, 0px, 0px); content-visibility: visible;\">\r\n");
      out.write("										<defs>\r\n");
      out.write("											<clipPath id=\"__lottie_element_2\">\r\n");
      out.write("												<rect width=\"60\" height=\"60\" x=\"0\" y=\"0\"></rect>\r\n");
      out.write("											</clipPath>\r\n");
      out.write("										</defs>\r\n");
      out.write("										<g clip-path=\"url(#__lottie_element_2)\">\r\n");
      out.write("											<g transform=\"matrix(0.9800000190734863,0,0,0.9800000190734863,30,30)\" opacity=\"1\" style=\"display: block;\">\r\n");
      out.write("												<g opacity=\"1\" transform=\"matrix(3,0,0,3,0,0)\">\r\n");
      out.write("													<path fill=\"rgb(0,0,0)\" fill-opacity=\"0.48\" d=\" M0,8.550000190734863 C-4.71999979019165,8.550000190734863 -8.550000190734863,4.71999979019165 -8.550000190734863,0 C-8.550000190734863,-4.71999979019165 -4.71999979019165,-8.550000190734863 0,-8.550000190734863 C4.71999979019165,-8.550000190734863 8.550000190734863,-4.71999979019165 8.550000190734863,0 C8.550000190734863,4.71999979019165 4.71999979019165,8.550000190734863 0,8.550000190734863z M0,9.5 C5.25,9.5 9.5,5.25 9.5,0 C9.5,-5.25 5.25,-9.5 0,-9.5 C-5.25,-9.5 -9.5,-5.25 -9.5,0 C-9.5,5.25 -5.25,9.5 0,9.5z\"></path>\r\n");
      out.write("												</g>\r\n");
      out.write("											</g>\r\n");
      out.write("										</g>\r\n");
      out.write("									</svg> -->\r\n");
      out.write("								</div>\r\n");
      out.write("								<span>예약하고 싶은 숙소가 없어요</span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"radio-list__item\">\r\n");
      out.write("							<div class=\"select-item-area\">\r\n");
      out.write("								<div style=\"display: inline-block;vertical-align: text-top;width: 20px;height: 20px;overflow: hidden;margin-right: 12px;\">\r\n");
      out.write("									<input type=\"checkbox\">\r\n");
      out.write("									<!-- <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 60 60\" width=\"60\" height=\"60\" preserveAspectRatio=\"xMidYMid meet\" style=\"width: 100%; height: 100%; transform: translate3d(0px, 0px, 0px); content-visibility: visible;\">\r\n");
      out.write("										<defs>\r\n");
      out.write("											<clipPath id=\"__lottie_element_2\">\r\n");
      out.write("												<rect width=\"60\" height=\"60\" x=\"0\" y=\"0\"></rect>\r\n");
      out.write("											</clipPath>\r\n");
      out.write("										</defs>\r\n");
      out.write("										<g clip-path=\"url(#__lottie_element_2)\">\r\n");
      out.write("											<g transform=\"matrix(0.9800000190734863,0,0,0.9800000190734863,30,30)\" opacity=\"1\" style=\"display: block;\">\r\n");
      out.write("												<g opacity=\"1\" transform=\"matrix(3,0,0,3,0,0)\">\r\n");
      out.write("													<path fill=\"rgb(0,0,0)\" fill-opacity=\"0.48\" d=\" M0,8.550000190734863 C-4.71999979019165,8.550000190734863 -8.550000190734863,4.71999979019165 -8.550000190734863,0 C-8.550000190734863,-4.71999979019165 -4.71999979019165,-8.550000190734863 0,-8.550000190734863 C4.71999979019165,-8.550000190734863 8.550000190734863,-4.71999979019165 8.550000190734863,0 C8.550000190734863,4.71999979019165 4.71999979019165,8.550000190734863 0,8.550000190734863z M0,9.5 C5.25,9.5 9.5,5.25 9.5,0 C9.5,-5.25 5.25,-9.5 0,-9.5 C-5.25,-9.5 -9.5,-5.25 -9.5,0 C-9.5,5.25 -5.25,9.5 0,9.5z\"></path>\r\n");
      out.write("												</g>\r\n");
      out.write("											</g>\r\n");
      out.write("										</g>\r\n");
      out.write("									</svg> -->\r\n");
      out.write("								</div>\r\n");
      out.write("								<span>예약, 취소, 혜택받기 등 사용이 어려어요</span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"radio-list__item\">\r\n");
      out.write("							<div class=\"select-item-area\">\r\n");
      out.write("								<div style=\"display: inline-block;vertical-align: text-top;width: 20px;height: 20px;overflow: hidden;margin-right: 12px;\">\r\n");
      out.write("									<input type=\"checkbox\">\r\n");
      out.write("									<!-- <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 60 60\" width=\"60\" height=\"60\" preserveAspectRatio=\"xMidYMid meet\" style=\"width: 100%; height: 100%; transform: translate3d(0px, 0px, 0px); content-visibility: visible;\">\r\n");
      out.write("										<defs>\r\n");
      out.write("											<clipPath id=\"__lottie_element_2\">\r\n");
      out.write("												<rect width=\"60\" height=\"60\" x=\"0\" y=\"0\"></rect>\r\n");
      out.write("											</clipPath>\r\n");
      out.write("										</defs>\r\n");
      out.write("										<g clip-path=\"url(#__lottie_element_2)\">\r\n");
      out.write("											<g transform=\"matrix(0.9800000190734863,0,0,0.9800000190734863,30,30)\" opacity=\"1\" style=\"display: block;\">\r\n");
      out.write("												<g opacity=\"1\" transform=\"matrix(3,0,0,3,0,0)\">\r\n");
      out.write("													<path fill=\"rgb(0,0,0)\" fill-opacity=\"0.48\" d=\" M0,8.550000190734863 C-4.71999979019165,8.550000190734863 -8.550000190734863,4.71999979019165 -8.550000190734863,0 C-8.550000190734863,-4.71999979019165 -4.71999979019165,-8.550000190734863 0,-8.550000190734863 C4.71999979019165,-8.550000190734863 8.550000190734863,-4.71999979019165 8.550000190734863,0 C8.550000190734863,4.71999979019165 4.71999979019165,8.550000190734863 0,8.550000190734863z M0,9.5 C5.25,9.5 9.5,5.25 9.5,0 C9.5,-5.25 5.25,-9.5 0,-9.5 C-5.25,-9.5 -9.5,-5.25 -9.5,0 C-9.5,5.25 -5.25,9.5 0,9.5z\"></path>\r\n");
      out.write("												</g>\r\n");
      out.write("											</g>\r\n");
      out.write("										</g>\r\n");
      out.write("									</svg> -->\r\n");
      out.write("								</div>\r\n");
      out.write("								<span>혜택(쿠폰,포인트)이 너무 적어요</span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"radio-list__item\">\r\n");
      out.write("							<div class=\"select-item-area\">\r\n");
      out.write("								<div style=\"display: inline-block;vertical-align: text-top;width: 20px;height: 20px;overflow: hidden;margin-right: 12px;\">\r\n");
      out.write("									<input type=\"checkbox\">\r\n");
      out.write("									<!-- <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 60 60\" width=\"60\" height=\"60\" preserveAspectRatio=\"xMidYMid meet\" style=\"width: 100%; height: 100%; transform: translate3d(0px, 0px, 0px); content-visibility: visible;\">\r\n");
      out.write("										<defs>\r\n");
      out.write("											<clipPath id=\"__lottie_element_2\">\r\n");
      out.write("												<rect width=\"60\" height=\"60\" x=\"0\" y=\"0\"></rect>\r\n");
      out.write("											</clipPath>\r\n");
      out.write("										</defs>\r\n");
      out.write("										<g clip-path=\"url(#__lottie_element_2)\">\r\n");
      out.write("											<g transform=\"matrix(0.9800000190734863,0,0,0.9800000190734863,30,30)\" opacity=\"1\" style=\"display: block;\">\r\n");
      out.write("												<g opacity=\"1\" transform=\"matrix(3,0,0,3,0,0)\">\r\n");
      out.write("													<path fill=\"rgb(0,0,0)\" fill-opacity=\"0.48\" d=\" M0,8.550000190734863 C-4.71999979019165,8.550000190734863 -8.550000190734863,4.71999979019165 -8.550000190734863,0 C-8.550000190734863,-4.71999979019165 -4.71999979019165,-8.550000190734863 0,-8.550000190734863 C4.71999979019165,-8.550000190734863 8.550000190734863,-4.71999979019165 8.550000190734863,0 C8.550000190734863,4.71999979019165 4.71999979019165,8.550000190734863 0,8.550000190734863z M0,9.5 C5.25,9.5 9.5,5.25 9.5,0 C9.5,-5.25 5.25,-9.5 0,-9.5 C-5.25,-9.5 -9.5,-5.25 -9.5,0 C-9.5,5.25 -5.25,9.5 0,9.5z\"></path>\r\n");
      out.write("												</g>\r\n");
      out.write("											</g>\r\n");
      out.write("										</g>\r\n");
      out.write("									</svg> -->\r\n");
      out.write("								</div>\r\n");
      out.write("								<span>개인정보 보호를 위해 삭제할 정보가 있어요</span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"radio-list__item\">\r\n");
      out.write("							<div class=\"select-item-area\">\r\n");
      out.write("								<div style=\"display: inline-block;vertical-align: text-top;width: 20px;height: 20px;overflow: hidden;margin-right: 12px;\">\r\n");
      out.write("									<input type=\"checkbox\">\r\n");
      out.write("									<!-- <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 60 60\" width=\"60\" height=\"60\" preserveAspectRatio=\"xMidYMid meet\" style=\"width: 100%; height: 100%; transform: translate3d(0px, 0px, 0px); content-visibility: visible;\">\r\n");
      out.write("										<defs>\r\n");
      out.write("											<clipPath id=\"__lottie_element_2\">\r\n");
      out.write("												<rect width=\"60\" height=\"60\" x=\"0\" y=\"0\"></rect>\r\n");
      out.write("											</clipPath>\r\n");
      out.write("										</defs>\r\n");
      out.write("										<g clip-path=\"url(#__lottie_element_2)\">\r\n");
      out.write("											<g transform=\"matrix(0.9800000190734863,0,0,0.9800000190734863,30,30)\" opacity=\"1\" style=\"display: block;\">\r\n");
      out.write("												<g opacity=\"1\" transform=\"matrix(3,0,0,3,0,0)\">\r\n");
      out.write("													<path fill=\"rgb(0,0,0)\" fill-opacity=\"0.48\" d=\" M0,8.550000190734863 C-4.71999979019165,8.550000190734863 -8.550000190734863,4.71999979019165 -8.550000190734863,0 C-8.550000190734863,-4.71999979019165 -4.71999979019165,-8.550000190734863 0,-8.550000190734863 C4.71999979019165,-8.550000190734863 8.550000190734863,-4.71999979019165 8.550000190734863,0 C8.550000190734863,4.71999979019165 4.71999979019165,8.550000190734863 0,8.550000190734863z M0,9.5 C5.25,9.5 9.5,5.25 9.5,0 C9.5,-5.25 5.25,-9.5 0,-9.5 C-5.25,-9.5 -9.5,-5.25 -9.5,0 C-9.5,5.25 -5.25,9.5 0,9.5z\"></path>\r\n");
      out.write("												</g>\r\n");
      out.write("											</g>\r\n");
      out.write("										</g>\r\n");
      out.write("									</svg> -->\r\n");
      out.write("								</div>\r\n");
      out.write("								<span>예약하고 싶은 숙소가 없어요</span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"radio-list__item\">\r\n");
      out.write("							<div class=\"select-item-area\">\r\n");
      out.write("								<div style=\"display: inline-block;vertical-align: text-top;width: 20px;height: 20px;overflow: hidden;margin-right: 12px;\">\r\n");
      out.write("									<input type=\"checkbox\">\r\n");
      out.write("									<!-- <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 60 60\" width=\"60\" height=\"60\" preserveAspectRatio=\"xMidYMid meet\" style=\"width: 100%; height: 100%; transform: translate3d(0px, 0px, 0px); content-visibility: visible;\">\r\n");
      out.write("										<defs>\r\n");
      out.write("											<clipPath id=\"__lottie_element_2\">\r\n");
      out.write("												<rect width=\"60\" height=\"60\" x=\"0\" y=\"0\"></rect>\r\n");
      out.write("											</clipPath>\r\n");
      out.write("										</defs>\r\n");
      out.write("										<g clip-path=\"url(#__lottie_element_2)\">\r\n");
      out.write("											<g transform=\"matrix(0.9800000190734863,0,0,0.9800000190734863,30,30)\" opacity=\"1\" style=\"display: block;\">\r\n");
      out.write("												<g opacity=\"1\" transform=\"matrix(3,0,0,3,0,0)\">\r\n");
      out.write("													<path fill=\"rgb(0,0,0)\" fill-opacity=\"0.48\" d=\" M0,8.550000190734863 C-4.71999979019165,8.550000190734863 -8.550000190734863,4.71999979019165 -8.550000190734863,0 C-8.550000190734863,-4.71999979019165 -4.71999979019165,-8.550000190734863 0,-8.550000190734863 C4.71999979019165,-8.550000190734863 8.550000190734863,-4.71999979019165 8.550000190734863,0 C8.550000190734863,4.71999979019165 4.71999979019165,8.550000190734863 0,8.550000190734863z M0,9.5 C5.25,9.5 9.5,5.25 9.5,0 C9.5,-5.25 5.25,-9.5 0,-9.5 C-5.25,-9.5 -9.5,-5.25 -9.5,0 C-9.5,5.25 -5.25,9.5 0,9.5z\"></path>\r\n");
      out.write("												</g>\r\n");
      out.write("											</g>\r\n");
      out.write("										</g>\r\n");
      out.write("									</svg> -->\r\n");
      out.write("								</div>\r\n");
      out.write("								<span>다른 계정이 있어요</span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"radio-list__item\">\r\n");
      out.write("							<div class=\"select-item-area\">\r\n");
      out.write("								<div style=\"display: inline-block;vertical-align: text-top;width: 20px;height: 20px;overflow: hidden;margin-right: 12px;\">\r\n");
      out.write("									<input type=\"checkbox\">\r\n");
      out.write("									<!-- <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 60 60\" width=\"60\" height=\"60\" preserveAspectRatio=\"xMidYMid meet\" style=\"width: 100%; height: 100%; transform: translate3d(0px, 0px, 0px); content-visibility: visible;\">\r\n");
      out.write("										<defs>\r\n");
      out.write("											<clipPath id=\"__lottie_element_2\">\r\n");
      out.write("												<rect width=\"60\" height=\"60\" x=\"0\" y=\"0\"></rect>\r\n");
      out.write("											</clipPath>\r\n");
      out.write("										</defs>\r\n");
      out.write("										<g clip-path=\"url(#__lottie_element_2)\">\r\n");
      out.write("											<g transform=\"matrix(0.9800000190734863,0,0,0.9800000190734863,30,30)\" opacity=\"1\" style=\"display: block;\">\r\n");
      out.write("												<g opacity=\"1\" transform=\"matrix(3,0,0,3,0,0)\">\r\n");
      out.write("													<path fill=\"rgb(0,0,0)\" fill-opacity=\"0.48\" d=\" M0,8.550000190734863 C-4.71999979019165,8.550000190734863 -8.550000190734863,4.71999979019165 -8.550000190734863,0 C-8.550000190734863,-4.71999979019165 -4.71999979019165,-8.550000190734863 0,-8.550000190734863 C4.71999979019165,-8.550000190734863 8.550000190734863,-4.71999979019165 8.550000190734863,0 C8.550000190734863,4.71999979019165 4.71999979019165,8.550000190734863 0,8.550000190734863z M0,9.5 C5.25,9.5 9.5,5.25 9.5,0 C9.5,-5.25 5.25,-9.5 0,-9.5 C-5.25,-9.5 -9.5,-5.25 -9.5,0 C-9.5,5.25 -5.25,9.5 0,9.5z\"></path>\r\n");
      out.write("												</g>\r\n");
      out.write("											</g>\r\n");
      out.write("										</g>\r\n");
      out.write("									</svg> -->\r\n");
      out.write("								</div>\r\n");
      out.write("								<span>기타</span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<ul class=\"paragraph_size_m\">\r\n");
      out.write("						<li class=\"paragraph_list\">            \r\n");
      out.write("							무료(무상) 포인트는 숙박 및 레저·티켓 구매시 사용 가능해요.\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"paragraph_list\"> \r\n");
      out.write("						<b>등록된 리뷰는 자동으로 삭제되지 않아요.</b>           \r\n");
      out.write("							탈퇴 전 개별적으로 삭제해 주세요\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"paragraph_list\">           \r\n");
      out.write("							<b>계정 정보 및 찜 목록 등 서비스 이용정보는 복구가 불가</b> \r\n");
      out.write("							하며, 동일한 아이디로 24시간 이후 재가입이 가능해요.\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<div class=\"bottom-section\">\r\n");
      out.write("						<div class=\"checkbox-area\">\r\n");
      out.write("							<div class=\"checkbox\">\r\n");
      out.write("								<div style=\"display: inline-block;vertical-align: text-top;width: 20px;height: 20px;overflow: hidden;margin: 0px 8px 0px auto;\">\r\n");
      out.write("									<input type=\"checkbox\" class=\"lastinput\">\r\n");
      out.write("									<!-- <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 60 60\" width=\"60\" height=\"60\" preserveAspectRatio=\"xMidYMid meet\" style=\"width: 100%; height: 100%; transform: translate3d(0px, 0px, 0px); content-visibility: visible;\">\r\n");
      out.write("										<g clip-path=\"url(#__lottie_element_58)\">\r\n");
      out.write("											<g transform=\"matrix(0.949999988079071,0,0,0.949999988079071,30,30)\" opacity=\"1\" style=\"display: block;\">\r\n");
      out.write("												<g opacity=\"1\" transform=\"matrix(3,0,0,3,0,0)\">\r\n");
      out.write("													<path fill=\"rgb(0,0,0)\" fill-opacity=\"0.56\" d=\" M-6,-9 C-7.659999847412109,-9 -9,-7.659999847412109 -9,-6 C-9,-6 -9,6 -9,6 C-9,7.659999847412109 -7.659999847412109,9 -6,9 C-6,9 6,9 6,9 C7.659999847412109,9 9,7.659999847412109 9,6 C9,6 9,-6 9,-6 C9,-7.659999847412109 7.659999847412109,-9 6,-9 C6,-9 -6,-9 -6,-9z M-6,-10 C-6,-10 6,-10 6,-10 C8.210000038146973,-10 10,-8.210000038146973 10,-6 C10,-6 10,6 10,6 C10,8.210000038146973 8.210000038146973,10 6,10 C6,10 -6,10 -6,10 C-8.210000038146973,10 -10,8.210000038146973 -10,6 C-10,6 -10,-6 -10,-6 C-10,-8.210000038146973 -8.210000038146973,-10 -6,-10z\"></path>\r\n");
      out.write("												</g>\r\n");
      out.write("											</g>\r\n");
      out.write("										</g>\r\n");
      out.write("									</svg> -->\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<span class=\"checkbox-area__text\">위 주의사항을 모두 숙지했고,탈퇴에 동의합니다</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<form action=\"\">\r\n");
      out.write("						<button class=\"button\"> 진짜 안녕 </button></form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script src=\"../../static/js/joinout.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var svg = document.querySelector('#click');\r\n");
      out.write("svg.onclick = function(){\r\n");
      out.write("	svg.style.color = 'red';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
