/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-26 07:18:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.loginpage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class resetPW_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../../static/css/loginpage/resetPW.css\" type=\"text/css\">\r\n");
      out.write("<title>비밀번호 재설정|STAR</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div class=\"layer_fix layer_unfix pop_login pop_mem_reserve new-style-form\">\r\n");
      out.write("       <section>\r\n");
      out.write("           <form id=\"loginForm\" action=\"https://www.goodchoice.kr/user/passwdResetNewProcess\" autocomplete=\"off\" method=\"post\" novalidate=\"novalidate\">\r\n");
      out.write("               <input type=\"hidden\" name=\"returnUrl\" value=\"\">\r\n");
      out.write("               <input type=\"hidden\" name=\"yeogi_token\" value=\"a92d03737df39a50b22a2dcec4c64c41\">\r\n");
      out.write("   \r\n");
      out.write("               <strong class=\"sub_title\">새 비밀번호 설정</strong>\r\n");
      out.write("   \r\n");
      out.write("               <p class=\"txt_top\">\r\n");
      out.write("                   인증이 완료되었습니다.<br>\r\n");
      out.write("                   새로운 비밀번호를 입력해주세요.\r\n");
      out.write("               </p>\r\n");
      out.write("   \r\n");
      out.write("            <div class=\"inp_type_1 ico_pw form-errors form-password-rule input-pw-div\">\r\n");
      out.write("               <input type=\"password\" name=\"passwd\" placeholder=\"새 비밀번호\" id=\"new_pw\">\r\n");
      out.write("               <label id=\"new_pw_msg\" class=\"validate_msg_label\"></label>\r\n");
      out.write("            <button type=\"button\" class=\"reset_val\">초기화</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"inp_type_1 ico_pw form-errors\">\r\n");
      out.write("               <input type=\"password\" name=\"confirm_passwd\" id=\"new_pw_re\" placeholder=\"새 비밀번호 확인\">\r\n");
      out.write("               <label id=\"new_pw_re_msg\" class=\"validate_msg_label\"></label>\r\n");
      out.write("            <button type=\"button\" class=\"reset_val\">초기화</button>\r\n");
      out.write("            </div>\r\n");
      out.write("   \r\n");
      out.write("            <button type=\"button\" onclick=\"changePwSubmit();\" class=\"btn_link gra_left_right_red btn_user_submit\" disabled=\"\" style=\"background-color: rgb(250, 250, 250); color: rgba(0, 0, 0, 0.16); border: none;\">\r\n");
      out.write("               <span>비밀번호 변경</span>\r\n");
      out.write("            </button>\r\n");
      out.write("           </form>\r\n");
      out.write("       </section>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    $(\"#new_pw\").blur(function(){\r\n");
      out.write("\r\n");
      out.write("        var pass = $(\"#new_pw\").val();\r\n");
      out.write("    var passcheck = $(\"#new_pw_re\").val();\r\n");
      out.write("\r\n");
      out.write(" if(passcheck == pass){\r\n");
      out.write("    $(\"#new_pw_re_msg\").css('color','blue');\r\n");
      out.write("    $(\"#new_pw_re_msg\").text('비밀번호가 일치합니다.');\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write(" else if(passcheck != pass){\r\n");
      out.write("    $(\"#new_pw_re_msg\").css('color','red');\r\n");
      out.write("    $(\"#new_pw_re_msg\").text('비밀번호가 일치하지 않습니다.');\r\n");
      out.write("    return false;\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $(\"#new_pw_re\").blur(function(){\r\n");
      out.write("    \r\n");
      out.write("    var pass = $(\"#new_pw\").val();\r\n");
      out.write("    var passcheck = $(\"#new_pw_re\").val();\r\n");
      out.write("\r\n");
      out.write(" if(passcheck == pass){\r\n");
      out.write("    $(\"#new_pw_re_msg\").css('color','blue');\r\n");
      out.write("    $(\"#new_pw_re_msg\").text('비밀번호가 일치합니다.');\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write(" else if(passcheck != pass){\r\n");
      out.write("    $(\"#new_pw_re_msg\").css('color','red');\r\n");
      out.write("    $(\"#new_pw_re_msg\").text('비밀번호가 일치하지 않습니다.');\r\n");
      out.write("    return false;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
